"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from backend.db import build_databases, load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_env_file(BASE_DIR)


def _env_bool(name, default=False):
    """خواندن مقدار بولین از متغیر محیطی."""
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


# ---------------------------------------------------------------------------
# پیکربندی امنیتی (تمام مقادیر حساس از متغیرهای محیطی خوانده می‌شوند، نه از کد)
# ---------------------------------------------------------------------------

# حالت دیباگ؛ در تولید باید False باشد (پیش‌فرض توسعه: True).
DEBUG = _env_bool("DJANGO_DEBUG", True)

# SECURITY WARNING: کلید امنیتی هرگز در کد hard-code نمی‌شود.
#   - در تولید: باید از طریق DJANGO_SECRET_KEY تنظیم شود؛ در غیر این صورت خطا.
#   - در توسعه: اگر تنظیم نشده باشد، یک کلید موقت تصادفی تولید می‌شود (persist
#     نمی‌شود؛ بنابراین با هر ری‌استارت سرور، session‌ها باطل می‌شوند).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        from django.core.management.utils import get_random_secret_key

        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            "متغیر محیطی DJANGO_SECRET_KEY باید در محیط تولید تنظیم شود."
        )

# دامنه‌های مجاز از متغیر محیطی (جداشده با کاما).
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth.apps.AuthConfig',
    'backend.apps.BackendConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# پیش‌فرض: MySQL — برای SQLite مقدار DB_ENGINE=sqlite بگذارید.

DATABASES = build_databases(BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# تنظیمات سفارشی پروژه (قابل override از طریق متغیرهای محیطی)
# ---------------------------------------------------------------------------

# آدرس فرانت‌اند React در حالت توسعه (برای CORS در صورت عدم استفاده از proxy).
FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", "http://localhost:5173")

# درگاه پیامک: پیش‌فرض «موک/شبیه‌سازی» است و هیچ پیامک واقعی ارسال نمی‌کند.
# برای اتصال درگاه واقعی، کلاسی سازگار با logic.sms.BaseSmsGateway بسازید و
# مسیر آن را در متغیر محیطی SMS_GATEWAY قرار دهید (مثلاً logic.sms.GenericHttpSmsGateway)
# و اعتبارنامه‌ها را در SMS_API_KEY و SMS_SENDER تنظیم کنید.
SMS_GATEWAY = os.environ.get("SMS_GATEWAY", "logic.sms.MockSmsGateway")
SMS_API_KEY = os.environ.get("SMS_API_KEY", "")
SMS_SENDER = os.environ.get("SMS_SENDER", "")

# در تولید با HTTPS مقدار true بگذارید؛ برای Docker/HTTP محلی false.
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
