# Generated by Django 6.0.6 on 2026-09-14 22:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from backend.migration_utils import (
    install_mysql_guards,
    remove_mysql_guards,
    seed_reference_data,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingMode',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEntityType',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdaySmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('message_template', models.TextField(default='تولدت مبارک {name}! از طرف {shop_name} بهترین\u200cها را برایت آرزومندیم.')),
                ('shop_name', models.CharField(default='سام اکسون', max_length=100)),
                ('send_time', models.TimeField(default=datetime.time(10, 0))),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='کد شعبه')),
                ('label', models.CharField(max_length=80, verbose_name='نام شعبه')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='رنگ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('membership_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntryStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntryType',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('office', 'اداری'), ('factory', 'کارخانه')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='📄', max_length=16)),
                ('page_key', models.SlugField(max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('system_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OrderKind',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('product_model', models.CharField(blank=True, max_length=100)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='عدد', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('default_price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, default='📦', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmsClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='سام اکسون', max_length=100)),
                ('auto_order_placed', models.BooleanField(default=True)),
                ('auto_welcome', models.BooleanField(default=True)),
                ('auto_level_up', models.BooleanField(default=True)),
                ('order_placed_template', models.TextField(default='{name} عزیز، سفارش شما به مبلغ {amount} ریال ثبت شد. {shop_name}')),
                ('welcome_template', models.TextField(default='{name} عزیز، به باشگاه {shop_name} خوش آمدید! کد عضویت شما: {code}')),
                ('level_up_template', models.TextField(default='{name} عزیز، سطح باشگاه شما به «{level}» ارتقا یافت. {shop_name}')),
                ('discount_template', models.TextField(default='{name} عزیز! تخفیف ویژه {discount_label} از {shop_name} — منتظر دیدار شما هستیم.')),
                ('default_discount_type', models.CharField(choices=[('amount', 'مبلغ ثابت'), ('percent', 'درصد')], default='amount', max_length=10)),
                ('default_discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsStatus',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsType',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('code', models.CharField(max_length=30)),
                ('path', models.CharField(editable=False, max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('account_class', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'سرمایه'), ('revenue', 'درآمد'), ('expense', 'هزینه')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار')], max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('legacy_entry_type', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='backend.account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='backend.ledger')),
            ],
            options={
                'ordering': ['ledger', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DetailedAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.account',),
        ),
        migrations.CreateModel(
            name='FactoryAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.account',),
        ),
        migrations.CreateModel(
            name='SubsidiaryAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.account',),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('approve', 'تایید'), ('reject', 'رد'), ('sale', 'فروش'), ('payment', 'دریافت پرداخت'), ('check_in', 'ثبت حضور'), ('check_out', 'پایان کار'), ('login', 'ورود'), ('logout', 'خروج'), ('sms', 'پیامک')], max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_executive_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type_ref', models.ForeignKey(blank=True, db_column='entity_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='backend.auditentitytype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.auditevent',),
        ),
        migrations.CreateModel(
            name='AuditUserTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_user_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdaySmsExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_sms_exclusions', to='backend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AuditCustomerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.PositiveBigIntegerField()),
                ('document_code', models.CharField(max_length=40)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transfer_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_journal', to='backend.journalentry')),
                ('status_ref', models.ForeignKey(db_column='status', default='draft', on_delete=django.db.models.deletion.PROTECT, to='backend.journalentrystatus')),
                ('entry_type_ref', models.ForeignKey(db_column='entry_type', default='manual', on_delete=django.db.models.deletion.PROTECT, to='backend.journalentrytype')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='backend.ledger')),
            ],
            options={
                'ordering': ['-entry_date', '-document_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('line_number', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='backend.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.journalentry')),
            ],
            options={
                'ordering': ['journal', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditJournalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.journalline')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.journalline',),
        ),
        migrations.CreateModel(
            name='LookupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'code'), name='uq_lookup_category_code')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('max_purchase', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_purchase'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_purchase__gte', 0)), name='ck_level_min'), models.CheckConstraint(condition=models.Q(('max_purchase__isnull', True), ('max_purchase__gte', models.F('min_purchase')), _connector='OR'), name='ck_level_range'), models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='ck_level_discount')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('total_purchases_at_change', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='backend.customer')),
                ('new_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.loyaltylevel')),
                ('previous_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.loyaltylevel')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='backend.loyaltylevel'),
        ),
        migrations.CreateModel(
            name='AuditLoyaltyLevelTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_level_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.loyaltylevel')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=150)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('color_hex', models.CharField(default='#cccccc', max_length=7)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50)),
                ('unit', models.CharField(default='متر', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('inventory_accounted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_materials', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_materials', to=settings.AUTH_USER_MODEL)),
                ('approval_status_ref', models.ForeignKey(db_column='approval_status', default='approved', on_delete=django.db.models.deletion.PROTECT, to='backend.materialstatus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditMaterialTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.material')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('pk', models.CompositePrimaryKey('menu_section', 'permission', blank=True, editable=False, primary_key=True, serialize=False)),
                ('menu_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menusection')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.permission')),
            ],
        ),
        migrations.CreateModel(
            name='OrgRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_ranks', to='backend.branch', to_field='code')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menusection',
            name='menu_permissions',
            field=models.ManyToManyField(blank=True, related_name='menu_sections', through='backend.MenuPermission', to='backend.permission'),
        ),
        migrations.CreateModel(
            name='AuditProductTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.productcategory'),
        ),
        migrations.CreateModel(
            name='AuditProductCategoryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('pk', models.CompositePrimaryKey('product', 'material', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='backend.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='backend.product')),
            ],
            options={
                'ordering': ['sort_order', 'product_id', 'material_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_hex', models.CharField(default='#cccccc', max_length=7)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='backend.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReminderCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('interval_months', models.PositiveIntegerField(default=3)),
                ('message_template', models.TextField(default='{name} عزیز، {shop_name} دلتنگ شماست! کد باشگاه: {code} — سطح: {level}')),
                ('shop_name', models.CharField(default='سام اکسون', max_length=100)),
                ('min_months_since_purchase', models.PositiveIntegerField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loyalty_levels', models.ManyToManyField(blank=True, related_name='reminder_campaigns', to='backend.loyaltylevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditReminderCampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_campaign_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.remindercampaign')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSendLog',
            fields=[
                ('pk', models.CompositePrimaryKey('campaign', 'customer', 'period_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='backend.remindercampaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='backend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('needs_branch', models.BooleanField(default=False)),
                ('grants_full_access', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='backend.roledefinition')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoleClosure',
            fields=[
                ('pk', models.CompositePrimaryKey('ancestor', 'descendant', blank=True, editable=False, primary_key=True, serialize=False)),
                ('depth', models.PositiveIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_descendants', to='backend.roledefinition')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_ancestors', to='backend.roledefinition')),
            ],
        ),
        migrations.CreateModel(
            name='AuditRoleDefinitionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_definition_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.roledefinition')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('pk', models.CompositePrimaryKey('role', 'permission', blank=True, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.roledefinition')),
            ],
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='permission_set',
            field=models.ManyToManyField(blank=True, related_name='roles', through='backend.RolePermission', to='backend.permission'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغ ثابت'), ('wallet', 'موجودی حساب')], default='amount', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('branch_approved_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_approved_at', models.DateTimeField(blank=True, null=True)),
                ('factory_received_at', models.DateTimeField(blank=True, null=True)),
                ('production_done_at', models.DateTimeField(blank=True, null=True)),
                ('freight_received_at', models.DateTimeField(blank=True, null=True)),
                ('freight_completed_at', models.DateTimeField(blank=True, null=True)),
                ('office_released_at', models.DateTimeField(blank=True, null=True)),
                ('factory_released_at', models.DateTimeField(blank=True, null=True)),
                ('materials_deducted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approved_sales', to=settings.AUTH_USER_MODEL)),
                ('accounting_mode_ref', models.ForeignKey(db_column='accounting_mode', default='automatic', on_delete=django.db.models.deletion.PROTECT, to='backend.accountingmode')),
                ('branch', models.ForeignKey(db_column='branch', default='branch_1', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='backend.branch', to_field='code')),
                ('branch_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_approved_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='backend.customer')),
                ('factory_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_received_sales', to=settings.AUTH_USER_MODEL)),
                ('freight_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_received_sales', to=settings.AUTH_USER_MODEL)),
                ('order_kind_ref', models.ForeignKey(db_column='order_kind', default='normal', on_delete=django.db.models.deletion.PROTECT, to='backend.orderkind')),
                ('order_status_ref', models.ForeignKey(db_column='order_status', default='confirmed', on_delete=django.db.models.deletion.PROTECT, to='backend.orderstatus')),
                ('payment_method_ref', models.ForeignKey(db_column='payment_method', default='cash', on_delete=django.db.models.deletion.PROTECT, to='backend.paymentmethod')),
                ('payment_status_ref', models.ForeignKey(db_column='payment_status', default='paid', on_delete=django.db.models.deletion.PROTECT, to='backend.paymentstatus')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalOrderLink',
            fields=[
                ('pk', models.CompositePrimaryKey('journal', 'order', 'relation_type', blank=True, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(default='source', max_length=30)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='backend.journalentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_links', to='backend.sale')),
            ],
        ),
        migrations.CreateModel(
            name='AuditOrderTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.sale')),
            ],
        ),
        migrations.CreateModel(
            name='AuditOfficeOrderTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_order_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.sale')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFactoryOrderTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_order_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.sale')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sale',),
        ),
        migrations.CreateModel(
            name='OfficeOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sale',),
        ),
        migrations.CreateModel(
            name='SaleInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('due_date', models.DateField()),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=120)),
                ('accounting_registered_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_checks', to='backend.journalentry')),
                ('deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_deposits', to='backend.account')),
                ('payment_method_ref', models.ForeignKey(db_column='payment_method', default='cash', on_delete=django.db.models.deletion.PROTECT, to='backend.paymentmethod')),
                ('registration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_registrations', to='backend.account')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='backend.sale')),
                ('status_ref', models.ForeignKey(db_column='status', default='pending', on_delete=django.db.models.deletion.PROTECT, to='backend.installmentstatus')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditInstallmentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.saleinstallment')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOrderInstallment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.saleinstallment',),
        ),
        migrations.CreateModel(
            name='OfficeOrderInstallment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.saleinstallment',),
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_model', models.CharField(blank=True, max_length=100)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='backend.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='backend.sale')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='backend.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=80)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='backend.material')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='backend.productvariant')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='backend.salelineitem')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOrderLineItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.salelineitem',),
        ),
        migrations.CreateModel(
            name='OfficeOrderLineItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.salelineitem',),
        ),
        migrations.CreateModel(
            name='SectionPermission',
            fields=[
                ('pk', models.CompositePrimaryKey('menu_section', 'permission', blank=True, editable=False, primary_key=True, serialize=False)),
                ('menu_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menusection')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.permission')),
            ],
        ),
        migrations.AddField(
            model_name='menusection',
            name='section_permissions',
            field=models.ManyToManyField(blank=True, related_name='protected_sections', through='backend.SectionPermission', to='backend.permission'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('full_name', models.CharField(max_length=150)),
                ('staff_kind', models.CharField(choices=[('seller', 'فروشنده'), ('manager', 'مدیر')], db_index=True, default='seller', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(db_column='branch', default='branch_1', on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='backend.branch', to_field='code')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='backend.seller'),
        ),
        migrations.CreateModel(
            name='AuditSellerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('provider_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='backend.customer')),
                ('status_ref', models.ForeignKey(db_column='status', default='pending', on_delete=django.db.models.deletion.PROTECT, to='backend.smsstatus')),
                ('sms_type_ref', models.ForeignKey(db_column='sms_type', default='manual', on_delete=django.db.models.deletion.PROTECT, to='backend.smstype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status_ref', models.ForeignKey(db_column='approval_status', default='approved', on_delete=django.db.models.deletion.PROTECT, to='backend.approvalstatus')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='backend.seller')),
                ('status_ref', models.ForeignKey(db_column='status', default='present', on_delete=django.db.models.deletion.PROTECT, to='backend.attendancestatus')),
                ('work_branch', models.ForeignKey(blank=True, db_column='work_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='backend.branch', to_field='code')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditAttendanceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_target', to='backend.auditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.staffattendance')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(db_column='branch', default='branch_1', on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='backend.branch', to_field='code')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('org_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='backend.orgrank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_check_deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_check_deposit', to='backend.account')),
                ('default_check_registration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_check_registration', to='backend.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('pk', models.CompositePrimaryKey('access_profile', 'permission', blank=True, editable=False, primary_key=True, serialize=False)),
                ('access_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.useraccessprofile')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.permission')),
            ],
        ),
        migrations.AddField(
            model_name='useraccessprofile',
            name='permission_set',
            field=models.ManyToManyField(blank=True, related_name='users', through='backend.UserPermission', to='backend.permission'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('sale', 'پرداخت فروش'), ('refund', 'بازگشت'), ('adjustment', 'اصلاح')], default='adjustment', max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='backend.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='backend.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='workflow_stage',
            field=models.ForeignKey(db_column='workflow_stage', default='completed', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='backend.workflowstage', to_field='code'),
        ),
        migrations.CreateModel(
            name='OrderTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='backend.sale')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backend.workflowstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='backend.workflowstage')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryDetailedAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.detailedaccount',),
        ),
        migrations.CreateModel(
            name='FactorySubsidiaryAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.subsidiaryaccount',),
        ),
        migrations.CreateModel(
            name='AccountClosure',
            fields=[
                ('pk', models.CompositePrimaryKey('ancestor', 'descendant', blank=True, editable=False, primary_key=True, serialize=False)),
                ('depth', models.PositiveIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_paths', to='backend.account')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_paths', to='backend.account')),
            ],
            options={
                'indexes': [models.Index(fields=['descendant', 'depth'], name='ix_account_ancestor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('depth__gte', 0)), name='ck_account_depth')],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'created_at'], name='ix_audit_action_date'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'created_at'], name='ix_audit_user_date'),
        ),
        migrations.AddConstraint(
            model_name='birthdaysmsexclusion',
            constraint=models.UniqueConstraint(fields=('customer', 'exclude_date'), name='uq_birthday_exclusion'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'journal'], name='ix_journal_line_account'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('journal', 'line_number'), name='uq_journal_line_no'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ck_journal_one_side'),
        ),
        migrations.CreateModel(
            name='FactoryAccountingEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.accountingentry',),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ledger', 'status_ref', 'entry_date'], name='ix_journal_ledger_date'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('ledger', 'document_number'), name='uq_journal_document_number'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('ledger', 'document_code'), name='uq_journal_document_code'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['ledger', 'parent', 'sort_order'], name='ix_account_tree'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('ledger', 'slug'), name='uq_account_ledger_slug'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('ledger', 'path'), name='uq_account_ledger_path'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_account_code_nonempty'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'joined_at'], name='ix_customer_active_join'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_material_cost'),
        ),
        migrations.AddConstraint(
            model_name='orgrank',
            constraint=models.UniqueConstraint(fields=('name', 'branch'), name='uq_rank_name_branch'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('default_price__gte', 0)), name='ck_product_price'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_bom_quantity'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color_name'), name='uq_variant_color'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ck_variant_price'),
        ),
        migrations.AddIndex(
            model_name='roleclosure',
            index=models.Index(fields=['descendant', 'depth'], name='ix_role_desc_depth'),
        ),
        migrations.AddConstraint(
            model_name='roleclosure',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 0)), name='ck_role_depth_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='saleinstallment',
            index=models.Index(fields=['status_ref', 'due_date'], name='ix_installment_due'),
        ),
        migrations.AddIndex(
            model_name='saleinstallment',
            index=models.Index(fields=['sale', 'due_date'], name='ix_installment_order'),
        ),
        migrations.AddConstraint(
            model_name='saleinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_installment_amount'),
        ),
        migrations.AddConstraint(
            model_name='saleinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method_ref_id', 'check'), models.Q(('check_number', ''), ('bank_name', '')), _connector='OR'), name='ck_installment_check_fields'),
        ),
        migrations.AddIndex(
            model_name='salelineitem',
            index=models.Index(fields=['sale', 'id'], name='ix_order_line_order'),
        ),
        migrations.AddConstraint(
            model_name='salelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_line_quantity'),
        ),
        migrations.AddConstraint(
            model_name='salelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_line_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='salelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='ck_line_total'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['material', 'created_at'], name='ix_inventory_material'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['variant', 'created_at'], name='ix_inventory_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('variant__isnull', True)), models.Q(('material__isnull', True), ('variant__isnull', False)), _connector='OR'), name='ck_inventory_one_item'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='ck_inventory_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_inventory_cost'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('seller', 'date'), name='uq_seller_attendance_date'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_in_at__isnull', False), _connector='OR'), name='ck_attendance_checkout'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['customer', 'created_at'], name='ix_wallet_customer_date'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_wallet_amount_nonzero'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'workflow_stage', 'sold_at'], name='ix_order_queue'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'sold_at'], name='ix_order_customer_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['order_status_ref', 'sold_at'], name='ix_order_status_date'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_order_amount'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='ck_order_discount'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gte', 0)), name='ck_order_final'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='ck_order_paid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('final_amount'))), name='ck_order_paid_lte_final'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('branch', 'invoice_number'), name='uq_order_branch_invoice'),
        ),
        migrations.AddIndex(
            model_name='ordertransition',
            index=models.Index(fields=['order', 'occurred_at'], name='ix_transition_order_date'),
        ),
        migrations.AddIndex(
            model_name='ordertransition',
            index=models.Index(fields=['to_stage', 'occurred_at'], name='ix_transition_stage_date'),
        ),
        migrations.RunPython(seed_reference_data, migrations.RunPython.noop),
        migrations.RunPython(install_mysql_guards, remove_mysql_guards),
    ]
