# Generated by Django 6.0.6 on 2026-07-02 23:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام کامل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات داخلی')),
                ('total_purchases', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مجموع کل خرید')),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تاریخ خرید')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام سطح')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, help_text='مجموع خرید بزرگ\u200cتر یا مساوی این مقدار، شرط ورود به سطح است.', max_digits=18, verbose_name='حداقل خرید')),
                ('max_purchase', models.DecimalField(blank=True, decimal_places=0, help_text='اختیاری. خالی بگذارید تا این سطح بالاترین سطح (بدون سقف) باشد.', max_digits=18, null=True, verbose_name='حداکثر خرید')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('points', models.IntegerField(default=0, verbose_name='امتیاز سطح')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='رنگ نمایشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سطح باشگاه',
                'verbose_name_plural': 'سطوح باشگاه',
                'ordering': ['min_purchase'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل تغییر')),
                ('total_purchases_at_change', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مجموع خرید در زمان تغییر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='backend.customer', verbose_name='مشتری')),
                ('new_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.loyaltylevel', verbose_name='سطح جدید')),
                ('previous_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.loyaltylevel', verbose_name='سطح قبلی')),
            ],
            options={
                'verbose_name': 'تاریخچه سطح مشتری',
                'verbose_name_plural': 'تاریخچه سطوح مشتریان',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='backend.loyaltylevel', verbose_name='سطح فعلی'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ فروش')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ نهایی')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فروش')),
                ('invoice_number', models.CharField(blank=True, max_length=40, verbose_name='شماره فاکتور')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('unpaid', 'پرداخت\u200cنشده'), ('partial', 'پرداخت بخشی')], default='paid', max_length=10, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('online', 'آنلاین'), ('credit', 'اعتباری')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='backend.customer', verbose_name='مشتری')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sales', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش\u200cها',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('sale', 'فروش'), ('refund', 'مرجوعی'), ('adjustment', 'اصلاح'), ('other', 'سایر')], default='sale', max_length=20, verbose_name='نوع سند')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بستانکار')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ سند')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید حسابداری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='backend.sale', verbose_name='فروش مرتبط')),
            ],
            options={
                'verbose_name': 'سند حسابداری',
                'verbose_name_plural': 'اسناد حسابداری',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شد'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت ارسال')),
                ('sms_type', models.CharField(choices=[('manual', 'دستی'), ('welcome', 'خوش\u200cآمدگویی'), ('level_up', 'ارتقای سطح'), ('promotion', 'تبلیغاتی')], default='manual', max_length=20, verbose_name='نوع پیامک')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('error', models.TextField(blank=True, verbose_name='خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='backend.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
