# Generated by Django 6.0.6 on 2026-07-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('mock_sent', 'شبیه\u200cسازی (درگاه واقعی غیرفعال)'), ('pending_provider_config', 'در انتظار تنظیم درگاه')], default='pending', max_length=30, verbose_name='وضعیت ارسال'),
        ),
    ]
