# Generated by Django 6.0.6 on 2026-09-16 17:13

import backend.models.rfm
import django.db.models.deletion
from django.db import migrations, models


def seed_rfm_sms_type(apps, schema_editor):
    SmsType = apps.get_model("backend", "SmsType")
    SmsType.objects.update_or_create(
        code="rfm",
        defaults={"label": "بخش‌بندی RFM", "sort_order": 8, "is_active": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('r_scores', models.JSONField(default=list)),
                ('f_scores', models.JSONField(default=list)),
                ('m_scores', models.JSONField(default=list)),
                ('action_type', models.CharField(choices=[('playbook', 'نمایش راهنما'), ('call', 'تماس فروش'), ('sms', 'پیامک'), ('vip', 'دعوت VIP')], default='playbook', max_length=16)),
                ('action_title', models.CharField(blank=True, max_length=160)),
                ('action_body', models.TextField(blank=True)),
                ('no_discount', models.BooleanField(default=False)),
                ('auto_sms', models.BooleanField(default=False)),
                ('sms_template', models.TextField(blank=True)),
                ('sms_cooldown_days', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RfmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookback_days', models.PositiveIntegerField(default=730)),
                ('score_method', models.CharField(choices=[('quantile', 'پنجک (۱ تا ۵)'), ('threshold', 'آستانهٔ دستی')], default='quantile', max_length=16)),
                ('quantile_count', models.PositiveSmallIntegerField(default=5)),
                ('monetary_field', models.CharField(choices=[('final_amount', 'مبلغ نهایی فاکتور'), ('paid_amount', 'مبلغ پرداخت\u200cشده')], default='final_amount', max_length=16)),
                ('fm_window', models.CharField(choices=[('lookback', 'بازهٔ انتخاب\u200cشده'), ('lifetime', 'کل طول عمر مشتری')], default='lookback', max_length=16)),
                ('r_thresholds', models.JSONField(default=backend.models.rfm.default_r_thresholds)),
                ('f_thresholds', models.JSONField(default=backend.models.rfm.default_f_thresholds)),
                ('m_thresholds', models.JSONField(default=backend.models.rfm.default_m_thresholds)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RfmActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(default='sms', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_action_logs', to='backend.customer')),
                ('sms_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfm_action_logs', to='backend.smslog')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='backend.rfmsegment')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['customer', 'action_type', 'sent_at'], name='ix_rfm_action_customer')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRfmScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_raw', models.PositiveIntegerField(default=0)),
                ('f_raw', models.PositiveIntegerField(default=0)),
                ('m_raw', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('r_score', models.PositiveSmallIntegerField(default=1)),
                ('f_score', models.PositiveSmallIntegerField(default=1)),
                ('m_score', models.PositiveSmallIntegerField(default=1)),
                ('rfm_code', models.CharField(db_index=True, max_length=3)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_score', to='backend.customer')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_scores', to='backend.rfmsegment')),
            ],
            options={
                'indexes': [models.Index(fields=['segment', 'rfm_code'], name='ix_rfm_segment_code')],
            },
        ),
        migrations.RunPython(seed_rfm_sms_type, migrations.RunPython.noop),
    ]
