# Generated by Django 6.0.6 on 2026-07-03 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sale_paid_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AddField(
            model_name='loyaltylevel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='loyaltylevel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='loyaltylevel',
            name='max_purchase',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='حداکثر خرید'),
        ),
        migrations.AlterField(
            model_name='loyaltylevel',
            name='min_purchase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='حداقل خرید'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ پرداخت\u200cشده'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('online', 'آنلاین'), ('credit', 'اعتباری'), ('check', 'چک')], default='cash', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('unpaid', 'پرداخت\u200cنشده'), ('installment', 'قسطی')], default='paid', max_length=12, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='پیام خطا'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('mock_sent', 'شبیه\u200cسازی'), ('pending_provider_config', 'در انتظار تنظیم درگاه')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='SaleInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('online', 'آنلاین'), ('credit', 'اعتباری'), ('check', 'چک')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='شماره چک')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت\u200cشده'), ('cancelled', 'لغوشده')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='backend.sale', verbose_name='فروش')),
            ],
            options={
                'verbose_name': 'قسط فروش',
                'verbose_name_plural': 'اقساط فروش',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب')], default='present', max_length=10, verbose_name='وضعیت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='backend.customer', verbose_name='مشتری')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ['-date'],
                'unique_together': {('customer', 'date')},
            },
        ),
    ]
