# Generated by Django 6.0.6

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.fields import AddField
from django.db.migrations.operations.models import AddConstraint, AddIndex, CreateModel, RemoveConstraint
import django.db.models.deletion


INVENTORY_NO_UPDATE = """
CREATE TRIGGER trg_inventory_no_update BEFORE UPDATE ON backend_inventorytransaction
FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Inventory ledger is append-only'
"""

INVENTORY_NO_DELETE = """
CREATE TRIGGER trg_inventory_no_delete BEFORE DELETE ON backend_inventorytransaction
FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Inventory ledger is append-only'
"""


def _column_exists(schema_editor, table, column):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(f'PRAGMA table_info("{table}")')
            return any(row[1] == column for row in cursor.fetchall())
        cursor.execute(
            """
            SELECT 1 FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s
            """,
            [table, column],
        )
        return cursor.fetchone() is not None


def _table_exists(schema_editor, table):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = %s",
                [table],
            )
            return cursor.fetchone() is not None
        cursor.execute(
            """
            SELECT 1 FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s
            """,
            [table],
        )
        return cursor.fetchone() is not None


def _index_exists(schema_editor, table, name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(f'PRAGMA index_list("{table}")')
            return any(row[1] == name for row in cursor.fetchall())
        cursor.execute(
            """
            SELECT 1 FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s
            """,
            [table, name],
        )
        return cursor.fetchone() is not None


def _constraint_exists(schema_editor, table, name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(
                "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = %s",
                [table],
            )
            row = cursor.fetchone()
            return bool(row and name in (row[0] or ""))
        cursor.execute(
            """
            SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND CONSTRAINT_NAME = %s
            """,
            [table, name],
        )
        return cursor.fetchone() is not None


class AddFieldIfMissing(AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        if _column_exists(schema_editor, model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class CreateModelIfMissing(CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if _table_exists(schema_editor, model._meta.db_table):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfMissing(AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if _index_exists(schema_editor, model._meta.db_table, self.index.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfMissing(AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(RemoveConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def seed_location_and_leave(apps, schema_editor):
    Warehouse = apps.get_model("backend", "Warehouse")
    AttendanceStatus = apps.get_model("backend", "AttendanceStatus")
    LookupOption = apps.get_model("backend", "LookupOption")

    warehouse, _ = Warehouse.objects.get_or_create(
        code="central",
        defaults={"label": "انبار مرکزی", "sort_order": 0, "is_active": True},
    )
    AttendanceStatus.objects.update_or_create(
        code="leave",
        defaults={"label": "مرخصی", "sort_order": 2, "is_active": True},
    )
    LookupOption.objects.update_or_create(
        category="system",
        code="attendance_enforced",
        defaults={
            "label": "اجبار حضورغیاب برای ثبت سفارش",
            "sort_order": 0,
            "is_active": True,
            "meta": {"enabled": True},
        },
    )

    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "mysql":
            cursor.execute("DROP TRIGGER IF EXISTS trg_inventory_no_update")
            cursor.execute("DROP TRIGGER IF EXISTS trg_inventory_no_delete")
        cursor.execute(
            """
            UPDATE backend_inventorytransaction
            SET location_kind = 'warehouse', warehouse_id = %s, stock_branch = NULL
            WHERE variant_id IS NOT NULL
              AND (location_kind = '' OR location_kind IS NULL)
            """,
            [warehouse.pk],
        )
        if connection.vendor == "mysql":
            cursor.execute(INVENTORY_NO_UPDATE)
            cursor.execute(INVENTORY_NO_DELETE)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0004_rfm"),
    ]

    operations = [
        AddFieldIfMissing(
            model_name="branch",
            name="work_end",
            field=models.TimeField(blank=True, null=True, verbose_name="پایان ساعت کاری"),
        ),
        AddFieldIfMissing(
            model_name="branch",
            name="work_start",
            field=models.TimeField(blank=True, null=True, verbose_name="شروع ساعت کاری"),
        ),
        AddFieldIfMissing(
            model_name="inventorytransaction",
            name="location_kind",
            field=models.CharField(
                blank=True,
                choices=[("warehouse", "انبار"), ("branch", "شعبه")],
                default="",
                max_length=16,
            ),
        ),
        AddFieldIfMissing(
            model_name="inventorytransaction",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_movements",
                to="backend.warehouse",
            ),
        ),
        AddFieldIfMissing(
            model_name="inventorytransaction",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                db_column="stock_branch",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_movements",
                to="backend.branch",
                to_field="code",
            ),
        ),
        AddFieldIfMissing(
            model_name="sale",
            name="stock_source_kind",
            field=models.CharField(
                blank=True,
                choices=[("warehouse", "انبار"), ("branch", "شعبه")],
                default="",
                max_length=16,
            ),
        ),
        AddFieldIfMissing(
            model_name="sale",
            name="stock_source_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_source_sales",
                to="backend.warehouse",
            ),
        ),
        AddFieldIfMissing(
            model_name="sale",
            name="stock_source_branch",
            field=models.ForeignKey(
                blank=True,
                db_column="stock_source_branch",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_source_sales",
                to="backend.branch",
                to_field="code",
            ),
        ),
        CreateModelIfMissing(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("attendance", "حضور و غیاب"),
                            ("sales", "فروش"),
                            ("products", "محصولات"),
                            ("warehouse", "انبار"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                ("action_type", models.CharField(blank=True, max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("target_permission", models.CharField(blank=True, max_length=80)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        CreateModelIfMissing(
            name="NotificationReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="backend.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        AddIndexIfMissing(
            model_name="notification",
            index=models.Index(fields=["section", "created_at"], name="ix_notification_section"),
        ),
        AddIndexIfMissing(
            model_name="notificationreceipt",
            index=models.Index(fields=["user", "is_read", "notification"], name="ix_notif_receipt_user"),
        ),
        AddConstraintIfMissing(
            model_name="notificationreceipt",
            constraint=models.UniqueConstraint(
                fields=("notification", "user"), name="uq_notification_receipt_user"
            ),
        ),
        AddIndexIfMissing(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["variant", "location_kind", "warehouse"], name="ix_inventory_loc_wh"
            ),
        ),
        AddIndexIfMissing(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["variant", "location_kind", "branch"], name="ix_inventory_loc_br"
            ),
        ),
        migrations.RunPython(seed_location_and_leave, migrations.RunPython.noop),
        AddConstraintIfMissing(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("variant__isnull", True))
                    | (
                        models.Q(
                            ("location_kind", "warehouse"),
                            ("warehouse__isnull", False),
                            ("branch__isnull", True),
                        )
                        | models.Q(
                            ("location_kind", "branch"),
                            ("warehouse__isnull", True),
                            ("branch__isnull", False),
                        )
                    )
                ),
                name="ck_inventory_variant_location",
            ),
        ),
        RemoveConstraintIfExists(
            model_name="staffattendance",
            name="uq_seller_attendance_date",
        ),
        AddConstraintIfMissing(
            model_name="staffattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("check_out_at__isnull", True),
                    ("is_deleted", False),
                    ("status_ref", "present"),
                ),
                fields=("seller",),
                name="uq_seller_open_present_attendance",
            ),
        ),
    ]
