# Generated by Django 6.0.6 on 2026-07-03 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_extended_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب')], default='present', max_length=10, verbose_name='وضعیت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'حضور و غیاب فروشنده',
                'verbose_name_plural': 'حضور و غیاب فروشندگان',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('branch_1', 'شعبه ۱'), ('branch_2', 'شعبه ۲')], default='branch_1', max_length=20, verbose_name='شعبه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل پرسنل',
                'verbose_name_plural': 'پروفایل پرسنل',
            },
        ),
        migrations.DeleteModel(
            name='CustomerAttendance',
        ),
    ]
