# Generated by Django 6.0.6

from django.db import migrations, models


ROLE_DEPARTMENT = {
    "ceo": "managers",
    "admin": "managers",
    "co_ceo": "managers",
    "branch_supervisor": "shop",
    "sales_expert": "shop",
    "sales_manager": "shop",
    "operator": "shop",
    "accounting_finance": "office",
    "accountant": "office",
    "factory_supervisor": "factory",
    "freight_supervisor": "factory",
    "pending": "",
}


def seed_departments(apps, schema_editor):
    RoleDefinition = apps.get_model("backend", "RoleDefinition")
    UserAccessProfile = apps.get_model("backend", "UserAccessProfile")
    User = apps.get_model("auth", "User")

    for rd in RoleDefinition.objects.all():
        department = ROLE_DEPARTMENT.get(rd.slug, rd.department or "")
        if rd.department != department:
            rd.department = department
            rd.save(update_fields=["department"])

    role_by_slug = {rd.slug: rd.department for rd in RoleDefinition.objects.all()}
    existing = {
        profile.user_id: profile
        for profile in UserAccessProfile.objects.all()
    }
    for user in User.objects.all():
        group_names = set(user.groups.values_list("name", flat=True))
        department = ""
        if user.is_superuser:
            department = "managers"
        else:
            for slug, dept in ROLE_DEPARTMENT.items():
                if slug in group_names:
                    department = dept
                    break
            if not department:
                for slug in group_names:
                    if slug in role_by_slug:
                        department = role_by_slug[slug]
                        break
        profile = existing.get(user.id)
        if profile is None:
            UserAccessProfile.objects.create(user_id=user.id, primary_department=department)
        elif profile.primary_department != department:
            profile.primary_department = department
            profile.save(update_fields=["primary_department"])


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_location_stock_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="roledefinition",
            name="department",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="useraccessprofile",
            name="primary_department",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
    ]
