# Generated by Django 6.0.6 on 2026-09-18 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rfm_club_unify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('earn_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_usable_percent', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('redeem_mode', models.CharField(choices=[('auto_each_sale', 'هر فاکتور از مبلغ کم شود'), ('wallet_credit', 'شارژ یک\u200cباره کیف پول'), ('manual', 'بدون مصرف خودکار')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('earn', 'کسب'), ('spend', 'مصرف روی فاکتور'), ('wallet_credit', 'شارژ کیف پول'), ('reversal', 'برگشت')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashbackUnlockStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_purchase_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('extra_usable_percent', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['extra_purchase_percent', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغ ثابت'), ('wallet', 'موجودی حساب'), ('cashback', 'کش\u200cبک')], default='amount', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('sale', 'پرداخت فروش'), ('refund', 'بازگشت'), ('adjustment', 'اصلاح'), ('cashback', 'کش\u200cبک')], default='adjustment', max_length=16),
        ),
        migrations.AddField(
            model_name='cashbackprogram',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='cashback_programs', to='backend.rfmsegment'),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_transactions', to='backend.customer'),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='backend.cashbackprogram'),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashback_transactions', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='cashbackunlockstep',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_steps', to='backend.cashbackprogram'),
        ),
        migrations.AddIndex(
            model_name='cashbacktransaction',
            index=models.Index(fields=['customer', 'created_at'], name='ix_cashback_customer_date'),
        ),
        migrations.AddIndex(
            model_name='cashbacktransaction',
            index=models.Index(fields=['sale', 'transaction_type'], name='ix_cashback_sale_type'),
        ),
        migrations.AddConstraint(
            model_name='cashbacktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_cashback_amount_nonzero'),
        ),
    ]
