# Generated by Django 6.0.6 on 2026-07-03 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _seed(apps, schema_editor):
    import secrets

    from logic.role_definitions import seed_builtin_roles

    seed_builtin_roles()
    Customer = apps.get_model("backend", "Customer")
    existing = set(
        Customer.objects.exclude(membership_code__isnull=True).values_list("membership_code", flat=True)
    )
    for customer in Customer.objects.filter(membership_code__isnull=True):
        while True:
            code = "".join(secrets.choice("0123456789") for _ in range(8))
            if code not in existing:
                existing.add(code)
                break
        customer.membership_code = code
        customer.save(update_fields=["membership_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_wallet_sms_club'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='عنوان رتبه')),
                ('branch', models.CharField(blank=True, choices=[('branch_1', 'کمرد'), ('branch_2', 'پاسداران')], max_length=20, verbose_name='شعبه')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='رنگ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رتبه سازمانی',
                'verbose_name_plural': 'رتبه\u200cهای سازمانی',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='کد عضویت باشگاه'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان شغلی'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='مدیر مستقیم'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('approve', 'تایید'), ('reject', 'رد'), ('sale', 'فروش'), ('payment', 'دریافت پرداخت'), ('check_in', 'ثبت حضور'), ('check_out', 'پایان کار'), ('login', 'ورود'), ('logout', 'خروج'), ('sms', 'پیامک')], max_length=20, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='موجودی کیف پول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.CharField(blank=True, choices=[('branch_1', 'کمرد'), ('branch_2', 'پاسداران')], max_length=20, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='branch',
            field=models.CharField(choices=[('branch_1', 'کمرد'), ('branch_2', 'پاسداران')], default='branch_1', max_length=20, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='smsclubsettings',
            name='default_discount_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مقدار تخفیف پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='smsclubsettings',
            name='welcome_template',
            field=models.TextField(default='{name} عزیز، به باشگاه {shop_name} خوش آمدید! کد عضویت شما: {code}', verbose_name='قالب خوش\u200cآمدگویی'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(choices=[('manual', 'دستی'), ('welcome', 'خوش\u200cآمدگویی'), ('level_up', 'ارتقای سطح'), ('promotion', 'تبلیغاتی'), ('birthday', 'تبریک تولد'), ('order_placed', 'ثبت سفارش'), ('discount', 'تخفیف ویژه'), ('reminder', 'یادآوری باشگاه')], default='manual', max_length=20, verbose_name='نوع پیامک'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='work_branch',
            field=models.CharField(blank=True, choices=[('branch_1', 'کمرد'), ('branch_2', 'پاسداران')], max_length=20, verbose_name='شعبه کاری'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.CharField(choices=[('branch_1', 'کمرد'), ('branch_2', 'پاسداران')], default='branch_1', max_length=20, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ (مثبت=واریز)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='موجودی پس از تراکنش'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='org_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='backend.orgrank', verbose_name='رتبه سازمانی'),
        ),
        migrations.CreateModel(
            name='ReminderCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کمپین')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('interval_months', models.PositiveIntegerField(default=3, verbose_name='هر چند ماه یک\u200cبار')),
                ('message_template', models.TextField(default='{name} عزیز، {shop_name} دلتنگ شماست! کد باشگاه: {code} — سطح: {level}', verbose_name='قالب پیام')),
                ('shop_name', models.CharField(default='سام اکسون', max_length=100, verbose_name='نام فروشگاه')),
                ('min_months_since_purchase', models.PositiveIntegerField(blank=True, help_text='اختیاری — فقط مشتریانی که حداقل این مدت خرید نکرده\u200cاند', null=True, verbose_name='حداقل ماه از آخرین خرید')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('loyalty_levels', models.ManyToManyField(blank=True, help_text='خالی = همه سطوح', related_name='reminder_campaigns', to='backend.loyaltylevel', verbose_name='سطوح هدف')),
            ],
            options={
                'verbose_name': 'کمپین یادآوری',
                'verbose_name_plural': 'کمپین\u200cهای یادآوری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='شناسه')),
                ('label', models.CharField(max_length=80, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('permissions', models.JSONField(default=list, verbose_name='مجوزها')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='نقش پیش\u200cفرض')),
                ('needs_branch', models.BooleanField(default=False, verbose_name='نیاز به شعبه')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='رنگ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='backend.roledefinition', verbose_name='نقش والد')),
            ],
            options={
                'verbose_name': 'تعریف نقش',
                'verbose_name_plural': 'تعریف نقش\u200cها',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=20, verbose_name='دوره')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='backend.remindercampaign', verbose_name='کمپین')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='backend.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'لاگ یادآوری',
                'verbose_name_plural': 'لاگ\u200cهای یادآوری',
                'unique_together': {('campaign', 'customer', 'period_key')},
            },
        ),
        migrations.RunPython(_seed, migrations.RunPython.noop),
    ]
