# Generated by Django 6.0.6 on 2026-07-06 17:48

from decimal import Decimal

from django.db import migrations, models


def migrate_variant_prices_to_product(apps, schema_editor):
    Product = apps.get_model("backend", "Product")
    ProductVariant = apps.get_model("backend", "ProductVariant")
    for product in Product.objects.all():
        default_price = Decimal(product.default_price or 0)
        if default_price <= 0:
            variant = (
                ProductVariant.objects.filter(product=product, is_active=True, price__gt=0)
                .order_by("sort_order", "id")
                .first()
            )
            if variant:
                product.default_price = variant.price
                product.save(update_fields=["default_price"])
        ProductVariant.objects.filter(product=product).update(price=0)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_payment_method_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مقدار تخفیف (ورودی)'),
        ),
        migrations.RunPython(migrate_variant_prices_to_product, migrations.RunPython.noop),
    ]
