# Generated by Django 6.0.6 on 2026-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_product_single_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='کد شعبه')),
                ('label', models.CharField(max_length=80, verbose_name='نام شعبه')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='رنگ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.SlugField(max_length=40, unique=True, verbose_name='شناسه بخش')),
                ('label', models.CharField(max_length=80, verbose_name='عنوان')),
                ('icon', models.CharField(default='📄', max_length=16, verbose_name='آیکون')),
                ('page_key', models.SlugField(max_length=40, verbose_name='کلید صفحه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('system_admin', models.BooleanField(default=False, verbose_name='فقط مدیر سیستم')),
                ('menu_permission_codes', models.JSONField(default=list, verbose_name='مجوزهای منو')),
                ('section_permission_codes', models.JSONField(default=list, verbose_name='مجوزهای بخش')),
            ],
            options={
                'verbose_name': 'بخش منو',
                'verbose_name_plural': 'بخش\u200cهای منو',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='grants_full_access',
            field=models.BooleanField(default=False, verbose_name='دسترسی کامل'),
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='غیرقابل ویرایش'),
        ),
        migrations.AlterField(
            model_name='orgrank',
            name='branch',
            field=models.CharField(blank=True, max_length=40, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.CharField(blank=True, max_length=40, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='branch',
            field=models.CharField(default='branch_1', max_length=40, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='work_branch',
            field=models.CharField(blank=True, max_length=40, verbose_name='شعبه کاری'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.CharField(default='branch_1', max_length=40, verbose_name='شعبه'),
        ),
        migrations.CreateModel(
            name='LookupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=40, verbose_name='دسته')),
                ('code', models.CharField(max_length=40, verbose_name='کد')),
                ('label', models.CharField(max_length=80, verbose_name='عنوان')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
            ],
            options={
                'verbose_name': 'گزینه سیستم',
                'verbose_name_plural': 'گزینه\u200cهای سیستم',
                'ordering': ['category', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'code'), name='uniq_lookup_category_code')],
            },
        ),
    ]
