# Generated by Django 6.0.6 on 2026-07-09 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_existing_workflow_data(apps, schema_editor):
    Sale = apps.get_model("backend", "Sale")
    for sale in Sale.objects.filter(office_released_at__isnull=False).iterator():
        from logic.order_queues import migrate_office_to_factory_if_needed, migrate_sale_to_office_if_needed

        office = migrate_sale_to_office_if_needed(sale)
        if office:
            migrate_office_to_factory_if_needed(office)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_sale_workflow_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transferred_to_office_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='انتقال به جدول اداری'),
        ),
        migrations.CreateModel(
            name='FactoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('invoice_number', models.CharField(blank=True, max_length=40, verbose_name='شماره فاکتور')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('branch', models.CharField(blank=True, max_length=40, verbose_name='شعبه')),
                ('order_kind', models.CharField(choices=[('normal', 'فروش عادی'), ('pre_invoice', 'پیش\u200cفاکتور'), ('deposit', 'بیعانیه')], default='normal', max_length=12, verbose_name='نوع سفارش')),
                ('workflow_stage', models.CharField(choices=[('accounting_approved', 'ارسال به کارخانه'), ('in_production', 'در حال ساخت'), ('production_done', 'آماده باربری'), ('in_freight', 'در باربری'), ('completed', 'تکمیل شده')], db_index=True, default='accounting_approved', max_length=24, verbose_name='مرحله کارخانه')),
                ('accounting_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید اداری')),
                ('factory_received_at', models.DateTimeField(blank=True, null=True, verbose_name='دریافت کارخانه')),
                ('production_done_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان ساخت')),
                ('freight_received_at', models.DateTimeField(blank=True, null=True, verbose_name='دریافت باربری')),
                ('freight_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تکمیل باربری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('accounting_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approved_factory_orders', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده اداری')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_orders', to='backend.customer', verbose_name='مشتری')),
                ('factory_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_received_orders', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده کارخانه')),
                ('freight_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_received_orders', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده باربری')),
                ('source_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_orders', to='backend.sale', verbose_name='فروش مبدأ')),
            ],
            options={
                'verbose_name': 'سفارش کارخانه',
                'verbose_name_plural': 'سفارش\u200cهای کارخانه',
                'db_table': 'factory_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('product_model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('fabric', models.CharField(blank=True, max_length=100, verbose_name='پارچه')),
                ('color_name', models.CharField(blank=True, max_length=50, verbose_name='رنگ')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='کد رنگ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('factory_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='backend.factoryorder', verbose_name='سفارش کارخانه')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productvariant', verbose_name='تنوع')),
            ],
            options={
                'verbose_name': 'ردیف سفارش کارخانه',
                'verbose_name_plural': 'ردیف\u200cهای سفارش کارخانه',
                'db_table': 'factory_order_line_items',
            },
        ),
        migrations.CreateModel(
            name='OfficeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ فروش')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغ ثابت'), ('wallet', 'موجودی حساب')], default='amount', max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مقدار تخفیف (ورودی)')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف (تومان)')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ نهایی')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ پرداخت\u200cشده')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فروش')),
                ('invoice_number', models.CharField(blank=True, max_length=40, verbose_name='شماره فاکتور')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('unpaid', 'پرداخت\u200cنشده'), ('installment', 'قسطی')], default='paid', max_length=12, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('check', 'چک')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('order_kind', models.CharField(choices=[('normal', 'فروش عادی'), ('pre_invoice', 'پیش\u200cفاکتور'), ('deposit', 'بیعانیه')], default='normal', max_length=12, verbose_name='نوع سفارش')),
                ('order_status', models.CharField(choices=[('confirmed', 'تایید شده'), ('pending', 'در انتظار'), ('cancelled', 'لغو شده')], default='pending', max_length=12, verbose_name='وضعیت سفارش')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('branch', models.CharField(blank=True, max_length=40, verbose_name='شعبه')),
                ('branch_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سرپرست')),
                ('accounting_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید اداری')),
                ('status', models.CharField(choices=[('pending_accounting', 'منتظر تایید اداری'), ('released_to_factory', 'ارسال\u200cشده به کارخانه')], db_index=True, default='pending_accounting', max_length=24, verbose_name='وضعیت صف اداری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('accounting_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approved_office_orders', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده اداری')),
                ('branch_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_approved_office_orders', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده سرپرست')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_orders', to='backend.customer', verbose_name='مشتری')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_office_orders', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_orders', to='backend.seller', verbose_name='فروشنده')),
                ('source_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_order', to='backend.sale', verbose_name='فروش مبدأ')),
            ],
            options={
                'verbose_name': 'سفارش اداری',
                'verbose_name_plural': 'سفارش\u200cهای اداری',
                'db_table': 'office_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='source_office_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_order', to='backend.officeorder', verbose_name='سفارش اداری مبدأ'),
        ),
        migrations.CreateModel(
            name='OfficeOrderInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('check', 'چک')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='شماره چک')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت\u200cشده'), ('cancelled', 'لغوشده')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('office_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='backend.officeorder', verbose_name='سفارش اداری')),
            ],
            options={
                'verbose_name': 'قسط سفارش اداری',
                'verbose_name_plural': 'اقساط سفارش اداری',
                'db_table': 'office_order_installments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('product_model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('fabric', models.CharField(blank=True, max_length=100, verbose_name='پارچه')),
                ('color_name', models.CharField(blank=True, max_length=50, verbose_name='رنگ')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='کد رنگ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت واحد')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='جمع ردیف')),
                ('office_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='backend.officeorder', verbose_name='سفارش اداری')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productvariant', verbose_name='تنوع')),
            ],
            options={
                'verbose_name': 'ردیف سفارش اداری',
                'verbose_name_plural': 'ردیف\u200cهای سفارش اداری',
                'db_table': 'office_order_line_items',
            },
        ),
        migrations.RunPython(migrate_existing_workflow_data, migrations.RunPython.noop),
    ]
