# Generated by Django 6.0.6 on 2026-09-22 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_pending_review(apps, schema_editor):
    JournalEntryStatus = apps.get_model("backend", "JournalEntryStatus")
    JournalEntryStatus.objects.update_or_create(
        code="pending_review",
        defaults={"label": "در انتظار بررسی", "sort_order": 1, "is_active": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_material_stocktake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('production', 'تولید'), ('showroom', 'شوروم'), ('admin', 'اداری')], default='production', max_length=20)),
                ('allocation_base', models.CharField(choices=[('machine_hours', 'ساعات ماشین'), ('floor_area', 'متراژ'), ('labor_hours', 'ساعات کار'), ('direct_cost', 'بهای مستقیم')], default='machine_hours', max_length=20)),
                ('base_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('qty_remaining', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'ارسال برای بررسی'), ('override', 'ویرایش انسانی'), ('post', 'ثبت قطعی'), ('unpost', 'برگشت از ثبت'), ('void', 'ابطال')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('before_lines', models.JSONField(blank=True, default=list)),
                ('after_lines', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OverheadAllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('share_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['cost_center_id'],
            },
        ),
        migrations.CreateModel(
            name='OverheadPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('allocated', 'تسهیم\u200cشده')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UnidentifiedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('open', 'باز'), ('allocated', 'تخصیص\u200cشده')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WipClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('completed_units', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('ending_wip_units', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('equivalent_units', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='is_profit_center',
            field=models.BooleanField(default=True, verbose_name='مرکز درآمد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='backend.branch', to_field='code'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='override_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='reorder_point',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='material',
            name='valuation_method',
            field=models.CharField(choices=[('weighted_average', 'میانگین موزون'), ('fifo', 'FIFO')], default='weighted_average', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='target_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='normal_spoilage_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_override_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='workshoprecipematerial',
            name='normal_spoilage_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نرخ ضایعات عادی'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', 0), _connector='OR'), name='ck_customer_credit_limit'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_point__gte', 0)), name='ck_material_reorder'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('target_margin_percent__isnull', True), models.Q(('target_margin_percent__gte', 0), ('target_margin_percent__lte', 100)), _connector='OR'), name='ck_product_target_margin'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('normal_spoilage_rate__gte', 0), ('normal_spoilage_rate__lte', 100)), name='ck_bom_spoilage'),
        ),
        migrations.AddConstraint(
            model_name='workshoprecipematerial',
            constraint=models.CheckConstraint(condition=models.Q(('normal_spoilage_rate__gte', 0), ('normal_spoilage_rate__lte', 100)), name='ck_recipe_spoilage'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='backend.branch', to_field='code'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='backend.ledger'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='backend.costcenter'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='backend.material'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layers', to='backend.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='journalrevision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalrevision',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='backend.journalentry'),
        ),
        migrations.AddField(
            model_name='overheadallocationline',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_lines', to='backend.costcenter'),
        ),
        migrations.AddField(
            model_name='overheadperiod',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overhead_periods', to='backend.journalentry'),
        ),
        migrations.AddField(
            model_name='overheadperiod',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overhead_periods', to='backend.ledger'),
        ),
        migrations.AddField(
            model_name='overheadallocationline',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.overheadperiod'),
        ),
        migrations.AddField(
            model_name='unidentifieddeposit',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidentified_deposits', to='backend.account'),
        ),
        migrations.AddField(
            model_name='unidentifieddeposit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidentifieddeposit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidentified_deposits', to='backend.customer'),
        ),
        migrations.AddField(
            model_name='unidentifieddeposit',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidentified_deposits', to='backend.journalentry'),
        ),
        migrations.AddField(
            model_name='wipclose',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_closes', to='backend.ledger'),
        ),
        migrations.AddField(
            model_name='wipclose',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wip_closes', to='backend.product'),
        ),
        migrations.AddField(
            model_name='wipclose',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wip_closes', to='backend.workshoprecipe'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('ledger', 'code'), name='uq_cost_center_ledger_code'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gte', 0)), name='ck_cost_center_base'),
        ),
        migrations.AddConstraint(
            model_name='inventorycostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_cost_layer_unit'),
        ),
        migrations.AddConstraint(
            model_name='inventorycostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('qty_remaining__gte', 0)), name='ck_cost_layer_qty'),
        ),
        migrations.AddConstraint(
            model_name='overheadperiod',
            constraint=models.UniqueConstraint(fields=('ledger', 'year', 'month'), name='uq_overhead_period'),
        ),
        migrations.AddConstraint(
            model_name='overheadperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_overhead_month'),
        ),
        migrations.AddConstraint(
            model_name='overheadperiod',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_overhead_amount'),
        ),
        migrations.AddConstraint(
            model_name='overheadallocationline',
            constraint=models.UniqueConstraint(fields=('period', 'cost_center'), name='uq_overhead_center'),
        ),
        migrations.AddConstraint(
            model_name='unidentifieddeposit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_unidentified_amount'),
        ),
        migrations.AddConstraint(
            model_name='wipclose',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_wip_month'),
        ),
        migrations.AddConstraint(
            model_name='wipclose',
            constraint=models.CheckConstraint(condition=models.Q(('completed_units__gte', 0)), name='ck_wip_completed'),
        ),
        migrations.AddConstraint(
            model_name='wipclose',
            constraint=models.CheckConstraint(condition=models.Q(('ending_wip_units__gte', 0)), name='ck_wip_ending'),
        ),
        migrations.AddConstraint(
            model_name='wipclose',
            constraint=models.CheckConstraint(condition=models.Q(('percent_complete__gte', 0), ('percent_complete__lte', 100)), name='ck_wip_percent'),
        ),
        migrations.RunPython(seed_pending_review, migrations.RunPython.noop),
    ]
