# Generated by Django 6.0.6 on 2026-09-22 15:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_accounting_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('national_code', models.CharField(blank=True, max_length=10)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده')], default='pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('month', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('days_worked', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('absence_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month_number', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('purpose', models.TextField()),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده'), ('settled', 'تسویه شده')], default='pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('settlement_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('order_type', models.CharField(choices=[('production', 'سفارش تولید'), ('service', 'سفارش خدمات'), ('correction', 'اصلاحیه سفارش')], default='production', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('white', 'سفید - عادی'), ('yellow', 'زرد - فوری'), ('red', 'قرمز - بسیار فوری')], default='white', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('in_production', 'در حال تولید'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('product_model', models.CharField(blank=True, max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('cushion_notes', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-delivery_date', '-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('wood_color', models.CharField(blank=True, max_length=100)),
                ('panel_color', models.CharField(blank=True, max_length=100)),
                ('fabric_color', models.CharField(blank=True, max_length=100)),
                ('fabric_quality', models.CharField(blank=True, max_length=100)),
                ('fabric_code', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['production_order', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('transfer_date', models.DateField()),
                ('required_personnel', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('in_transit', 'در حال انتقال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('qc_approved', models.BooleanField(default=False)),
                ('qc_notes', models.TextField(blank=True)),
                ('has_defects', models.BooleanField(default=False)),
                ('defect_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='عدد', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('line_number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['transfer', 'line_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventorytransaction',
            name='ck_inventory_variant_location',
        ),
        migrations.AlterField(
            model_name='betaassemblyjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='betaassemblyjob',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='betacarpentryorder',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_carpentry_orders', to='backend.frame'),
        ),
        migrations.AlterField(
            model_name='betacarpentrywoodpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='betaclearancejob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='betaclearancejob',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='section',
            field=models.CharField(choices=[('attendance', 'حضور و غیاب'), ('sales', 'فروش'), ('products', 'محصولات'), ('warehouse', 'انبار'), ('org', 'سازمانی')], db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('variant__isnull', True), models.Q(('branch__isnull', True), ('location_kind', 'warehouse'), ('warehouse__isnull', False)), models.Q(('branch__isnull', False), ('location_kind', 'branch'), ('warehouse__isnull', True)), _connector='OR'), name='ck_inventory_variant_location'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assistance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceconfirmation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='productionorderline',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.productionorder'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='approved_by_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='approved_by_qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='approved_by_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='backend.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='backend.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousetransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.warehousetransfer'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['employee', 'status'], name='backend_ass_employe_8ef4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['status', 'request_date'], name='backend_ass_status_f961f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_assistance_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='attendanceconfirmation',
            index=models.Index(fields=['employee', 'year', 'month_number'], name='backend_att_employe_7d8291_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceconfirmation',
            index=models.Index(fields=['status', 'year', 'month_number'], name='backend_att_status_430cca_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceconfirmation',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month_number'), name='uq_attendance_employee_month'),
        ),
        migrations.AddConstraint(
            model_name='attendanceconfirmation',
            constraint=models.CheckConstraint(condition=models.Q(('days_worked__gte', 0), ('days_worked__lte', 31)), name='ck_days_worked_range'),
        ),
        migrations.AddConstraint(
            model_name='attendanceconfirmation',
            constraint=models.CheckConstraint(condition=models.Q(('overtime_hours__gte', 0)), name='ck_overtime_positive'),
        ),
        migrations.AddIndex(
            model_name='pettycashrequest',
            index=models.Index(fields=['requester', 'status'], name='backend_pet_request_cd31d4_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashrequest',
            index=models.Index(fields=['status', 'request_date'], name='backend_pet_status_db67ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='pettycashrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_petty_cash_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'priority', 'delivery_date'], name='backend_pro_status_ce8b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['sale'], name='backend_pro_sale_id_c7f6b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorderline',
            constraint=models.UniqueConstraint(fields=('production_order', 'line_number'), name='uq_production_order_line'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['from_warehouse', 'to_warehouse', 'status'], name='backend_war_from_wa_87a87c_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['status', 'transfer_date'], name='backend_war_status_158486_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousetransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'line_number'), name='uq_transfer_line'),
        ),
    ]
