# Generated by Django 6.0.6 on 2026-09-22 18:56

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum


def fill_public_uuids(apps, schema_editor):
    for model_name in ("Sale", "InventoryTransaction", "ProductionOrder"):
        model = apps.get_model("backend", model_name)
        pending = model.objects.filter(uuid__isnull=True).values_list("pk", flat=True)
        for pk in pending.iterator():
            model.objects.filter(pk=pk).update(uuid=uuid.uuid4())


def inherit_account_classification(apps, schema_editor):
    account_model = apps.get_model("backend", "Account")
    valid_classes = {"asset", "liability", "equity", "revenue", "expense"}
    valid_sides = {"debit", "credit"}
    for account in account_model.objects.exclude(parent_id=None).iterator():
        parent = account_model.objects.filter(pk=account.parent_id).first()
        if parent is None:
            continue
        updates = {}
        if account.account_class not in valid_classes:
            updates["account_class"] = parent.account_class
        if account.normal_balance not in valid_sides:
            updates["normal_balance"] = parent.normal_balance
        if updates:
            account_model.objects.filter(pk=account.pk).update(**updates)


def backfill_journal_totals(apps, schema_editor):
    journal_model = apps.get_model("backend", "JournalEntry")
    line_model = apps.get_model("backend", "JournalLine")
    for journal_id in journal_model.objects.values_list("pk", flat=True).iterator():
        totals = line_model.objects.filter(journal_id=journal_id).aggregate(
            debit=Sum("debit"), credit=Sum("credit")
        )
        journal_model.objects.filter(pk=journal_id).update(
            debit_total=totals["debit"] or Decimal("0"),
            credit_total=totals["credit"] or Decimal("0"),
        )


ORIGIN_UUID_TRIGGER = """
CREATE TRIGGER trg_origin_uuid_bi
BEFORE INSERT ON backend_accountingorigin
FOR EACH ROW
BEGIN
  DECLARE actual CHAR(32);
  DECLARE targets INT;
  SET targets = (NEW.sale_id IS NOT NULL) + (NEW.production_order_id IS NOT NULL) + (NEW.inventory_transaction_id IS NOT NULL);
  IF targets <> 1 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'accounting origin requires exactly one module target';
  END IF;
  IF NEW.module = 'sales' THEN
    IF NEW.sale_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'sales origin must reference a sale';
    END IF;
    SELECT `uuid` INTO actual FROM backend_sale WHERE id = NEW.sale_id;
  ELSEIF NEW.module = 'factory' AND NEW.production_order_id IS NOT NULL THEN
    IF NEW.sale_id IS NOT NULL OR NEW.inventory_transaction_id IS NOT NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'factory origin must reference one target';
    END IF;
    SELECT `uuid` INTO actual FROM backend_productionorder WHERE id = NEW.production_order_id;
  ELSEIF NEW.module = 'factory' AND NEW.sale_id IS NOT NULL THEN
    IF NEW.inventory_transaction_id IS NOT NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'factory origin must reference one target';
    END IF;
    SELECT `uuid` INTO actual FROM backend_sale WHERE id = NEW.sale_id;
  ELSEIF NEW.module = 'warehouse' THEN
    IF NEW.inventory_transaction_id IS NULL OR NEW.sale_id IS NOT NULL OR NEW.production_order_id IS NOT NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'warehouse origin must reference an inventory movement';
    END IF;
    SELECT `uuid` INTO actual FROM backend_inventorytransaction WHERE id = NEW.inventory_transaction_id;
  ELSE
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'unknown accounting origin module';
  END IF;
  IF actual IS NULL OR NEW.source_uuid <> actual THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'source_uuid must match the referenced module row';
  END IF;
END
"""

ORIGIN_UUID_UPDATE_TRIGGER = ORIGIN_UUID_TRIGGER.replace(
    "trg_origin_uuid_bi", "trg_origin_uuid_bu"
).replace("BEFORE INSERT", "BEFORE UPDATE")

JOURNAL_LINE_GUARD = """
CREATE TRIGGER trg_journal_line_bi
BEFORE INSERT ON backend_journalline
FOR EACH ROW
BEGIN
  DECLARE journal_ledger BIGINT;
  DECLARE account_ledger BIGINT;
  DECLARE account_active TINYINT;
  DECLARE child_count INT;
  DECLARE doc_status VARCHAR(32);
  SELECT ledger_id, status INTO journal_ledger, doc_status
    FROM backend_journalentry WHERE id = NEW.journal_id;
  SELECT ledger_id, is_active INTO account_ledger, account_active
    FROM backend_account WHERE id = NEW.account_id;
  SELECT COUNT(*) INTO child_count FROM backend_account WHERE parent_id = NEW.account_id;
  IF journal_ledger IS NULL OR account_ledger IS NULL OR journal_ledger <> account_ledger THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'account ledger must match journal ledger';
  END IF;
  IF account_active = 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'inactive account is not postable';
  END IF;
  IF child_count > 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'only leaf accounts are postable';
  END IF;
  IF doc_status = 'posted' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'posted journal lines are immutable';
  END IF;
END
"""

JOURNAL_LINE_UPDATE_GUARD = JOURNAL_LINE_GUARD.replace(
    "trg_journal_line_bi", "trg_journal_line_bu"
).replace("BEFORE INSERT", "BEFORE UPDATE")

JOURNAL_POST_GUARD = """
CREATE TRIGGER trg_journal_entry_bu
BEFORE UPDATE ON backend_journalentry
FOR EACH ROW
BEGIN
  DECLARE line_debit DECIMAL(18, 0);
  DECLARE line_credit DECIMAL(18, 0);
  IF OLD.status = 'posted' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'posted journal is immutable';
  END IF;
  IF NEW.status = 'posted' THEN
    SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
      INTO line_debit, line_credit
      FROM backend_journalline WHERE journal_id = NEW.id;
    IF line_debit <> line_credit
       OR line_debit <> NEW.debit_total
       OR line_credit <> NEW.credit_total
       OR line_debit <= 0 THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'posted journal must balance';
    END IF;
  END IF;
END
"""

TRIGGER_STATEMENTS = (
    ("trg_origin_uuid_bi", ORIGIN_UUID_TRIGGER),
    ("trg_origin_uuid_bu", ORIGIN_UUID_UPDATE_TRIGGER),
    ("trg_journal_line_bi", JOURNAL_LINE_GUARD),
    ("trg_journal_line_bu", JOURNAL_LINE_UPDATE_GUARD),
    ("trg_journal_entry_bu", JOURNAL_POST_GUARD),
)


def install_integrity_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, statement in TRIGGER_STATEMENTS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(statement)


def remove_integrity_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, _statement in TRIGGER_STATEMENTS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('backend', '0027_accounting_repair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'فروش'), ('factory', 'کارخانه'), ('warehouse', 'انبار')], max_length=16)),
                ('source_uuid', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'سرفصل سند',
                'verbose_name_plural': 'سرفصل\u200cهای سند',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.journalentry',),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(fill_public_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(inherit_account_classification, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('account_class__in', ['asset', 'liability', 'equity', 'revenue', 'expense'])), name='ck_account_class'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('normal_balance__in', ['debit', 'credit'])), name='ck_account_normal_balance'),
        ),
        migrations.RunPython(backfill_journal_totals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status_ref_id', 'posted'), _negated=True), ('debit_total', models.F('credit_total')), _connector='OR'), name='ck_journal_posted_balanced'),
        ),
        migrations.AddField(
            model_name='accountingorigin',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_origins', to='backend.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='accountingorigin',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_origins', to='backend.productionorder'),
        ),
        migrations.AddField(
            model_name='accountingorigin',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_origins', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='transactionsource',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_links', to='backend.accountingorigin'),
        ),
        migrations.AddField(
            model_name='transactionsource',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='backend.journalentry'),
        ),
        migrations.AddConstraint(
            model_name='accountingorigin',
            constraint=models.UniqueConstraint(fields=('module', 'source_uuid'), name='uq_origin_module_uuid'),
        ),
        migrations.AddConstraint(
            model_name='accountingorigin',
            constraint=models.UniqueConstraint(fields=('module', 'sale'), name='uq_origin_module_sale'),
        ),
        migrations.AddConstraint(
            model_name='accountingorigin',
            constraint=models.UniqueConstraint(fields=('production_order',), name='uq_origin_production'),
        ),
        migrations.AddConstraint(
            model_name='accountingorigin',
            constraint=models.UniqueConstraint(fields=('inventory_transaction',), name='uq_origin_inventory'),
        ),
        migrations.AddConstraint(
            model_name='accountingorigin',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_transaction__isnull', True), ('module', 'sales'), ('production_order__isnull', True), ('sale__isnull', False)), models.Q(('inventory_transaction__isnull', True), ('module', 'factory'), ('production_order__isnull', True), ('sale__isnull', False)), models.Q(('inventory_transaction__isnull', True), ('module', 'factory'), ('production_order__isnull', False), ('sale__isnull', True)), models.Q(('inventory_transaction__isnull', False), ('module', 'warehouse'), ('production_order__isnull', True), ('sale__isnull', True)), _connector='OR'), name='ck_origin_arc'),
        ),
        migrations.AddConstraint(
            model_name='transactionsource',
            constraint=models.UniqueConstraint(fields=('transaction', 'origin'), name='uq_tx_source'),
        ),
        migrations.RunPython(install_integrity_triggers, remove_integrity_triggers),
    ]
