# Generated by Django 6.0.6 on 2026-10-01 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_dropdown_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='betacarpentryworkshop',
            name='kind',
            field=models.CharField(choices=[('internal', 'داخل کارخانه'), ('satellite', 'بازرگان')], default='internal', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='furnitureworkset',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام سرویس'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'انجام نشده'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], db_index=True, default='todo', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, help_text='سررسید وظیفه', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_at', models.DateTimeField(blank=True, db_index=True, help_text='زمان یادآوری', null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(db_index=True, default=False, help_text='پین کردن برای اولویت بالا')),
                ('assigned_to', models.ForeignKey(help_text='کاربری که این وظیفه به او محول شده', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='کاربری که این وظیفه را ایجاد کرده', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='backend.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='backend.sale')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-pinned', '-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('email', 'ایمیل'), ('meeting', 'جلسه'), ('note', 'یادداشت'), ('sale', 'فروش'), ('task_created', 'وظیفه ایجاد شد'), ('task_completed', 'وظیفه انجام شد'), ('order_status', 'تغییر وضعیت سفارش'), ('customer_created', 'مشتری جدید')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='داده\u200cهای اضافی مانند مدت تماس، موضوع جلسه و ...')),
                ('occurred_at', models.DateTimeField(help_text='زمان وقوع فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='backend.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='backend.sale')),
                ('user', models.ForeignKey(help_text='کاربری که این فعالیت را ثبت کرده', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='backend.task')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status', '-due_date'], name='ix_task_assigned'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['pinned', '-priority'], name='ix_task_priority'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='ix_task_status'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-occurred_at'], name='ix_activity_user_date'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['customer', '-occurred_at'], name='ix_activity_customer'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-occurred_at'], name='ix_activity_type'),
        ),
    ]
