# Generated by Django 6.0.6 on 2026-10-01 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_activities_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stat_card', 'کارت آماری'), ('chart_bar', 'نمودار ستونی'), ('chart_line', 'نمودار خطی'), ('chart_pie', 'نمودار دایره\u200cای'), ('table', 'جدول')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('config', models.JSONField(blank=True, default=dict, help_text='تنظیمات ویجت: metric، time_range، filters و ...')),
                ('position', models.IntegerField(db_index=True, default=0, help_text='ترتیب نمایش ویجت')),
                ('size', models.CharField(choices=[('small', 'کوچک'), ('medium', 'متوسط'), ('large', 'بزرگ'), ('wide', 'عریض')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='کاربری که این ویجت را ساخته', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ویجت داشبورد',
                'verbose_name_plural': 'ویجت\u200cهای داشبورد',
                'ordering': ['user', 'position'],
                'indexes': [models.Index(fields=['user', 'position'], name='ix_widget_user_pos')],
            },
        ),
    ]
