# Generated by Django 6.0.6 on 2026-07-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_sale_accounting_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'حساب کل', 'verbose_name_plural': 'حساب\u200cهای کل'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_class',
            field=models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'سرمایه'), ('revenue', 'درآمد'), ('expense', 'هزینه')], max_length=20, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='backend.account', verbose_name='حساب کل'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='entry_type',
            field=models.CharField(choices=[('manual', 'دستی'), ('sale', 'فروش'), ('receivable', 'دریافتنی'), ('payment', 'دریافت / پرداخت'), ('refund', 'برگشت'), ('adjustment', 'تعدیل'), ('other', 'سایر')], default='sale', max_length=20, verbose_name='نوع سند'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='opening_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده ابتدای دوره (بستانکار)'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='opening_debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده ابتدای دوره (بدهکار)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='smsclubsettings',
            name='order_placed_template',
            field=models.TextField(default='{name} عزیز، سفارش شما به مبلغ {amount} ریال ثبت شد. {shop_name}', verbose_name='قالب ثبت سفارش'),
        ),
    ]
