# Generated by Django 6.0.6 on 2026-07-30 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_account_options_alter_account_account_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='شناسه')),
                ('code', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='کد حساب کل')),
                ('name', models.CharField(max_length=120, verbose_name='نام حساب')),
                ('account_class', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'سرمایه'), ('revenue', 'درآمد'), ('expense', 'هزینه')], max_length=20, verbose_name='طبقه')),
                ('normal_balance', models.CharField(choices=[('debit', 'بدهکار'), ('credit', 'بستانکار')], max_length=10, verbose_name='ماهیت')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('legacy_entry_type', models.CharField(blank=True, max_length=20, verbose_name='نوع سند قدیمی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب کل کارخانه',
                'verbose_name_plural': 'حساب\u200cهای کل کارخانه',
                'db_table': 'factory_accounts',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FactorySubsidiaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='کد معین')),
                ('name', models.CharField(max_length=120, verbose_name='عنوان حساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='backend.factoryaccount', verbose_name='حساب کل')),
            ],
            options={
                'verbose_name': 'حساب معین کارخانه',
                'verbose_name_plural': 'حساب\u200cهای معین کارخانه',
                'db_table': 'factory_subsidiary_accounts',
                'ordering': ['account__sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FactoryDetailedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='کد تفصیلی')),
                ('name', models.CharField(max_length=120, verbose_name='عنوان حساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='backend.factorysubsidiaryaccount', verbose_name='حساب معین')),
            ],
            options={
                'verbose_name': 'حساب تفصیلی کارخانه',
                'verbose_name_plural': 'حساب\u200cهای تفصیلی کارخانه',
                'db_table': 'factory_detailed_accounts',
                'ordering': ['subsidiary__account__sort_order', 'subsidiary__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FactoryAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('manual', 'دستی'), ('sale', 'فروش'), ('receivable', 'دریافتنی'), ('payment', 'دریافت / پرداخت'), ('refund', 'برگشت'), ('adjustment', 'تعدیل'), ('other', 'سایر')], default='adjustment', max_length=20, verbose_name='نوع سند')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بستانکار')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ')),
                ('document_code', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='کد سند')),
                ('document_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='شماره سند')),
                ('attach_code', models.CharField(blank=True, max_length=10, verbose_name='ع')),
                ('general_account', models.CharField(blank=True, max_length=120, verbose_name='حساب کل')),
                ('subsidiary_account', models.CharField(blank=True, max_length=120, verbose_name='حساب معین')),
                ('detailed_account', models.CharField(blank=True, max_length=120, verbose_name='حساب تفصیلی')),
                ('opening_debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده ابتدای دوره (بدهکار)')),
                ('opening_credit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده ابتدای دوره (بستانکار)')),
                ('balance_debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده بدهکار')),
                ('balance_credit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده بستانکار')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ سند')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید حسابداری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='backend.factoryaccount', verbose_name='حساب کل')),
                ('factory_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='backend.factoryorder', verbose_name='سفارش کارخانه')),
                ('detailed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='backend.factorydetailedaccount', verbose_name='حساب تفصیلی')),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='backend.factorysubsidiaryaccount', verbose_name='حساب معین')),
            ],
            options={
                'verbose_name': 'سند حسابداری کارخانه',
                'verbose_name_plural': 'اسناد حسابداری کارخانه',
                'db_table': 'factory_accounting_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='factorysubsidiaryaccount',
            constraint=models.UniqueConstraint(fields=('account', 'code'), name='uniq_factory_subsidiary_account_code'),
        ),
        migrations.AddConstraint(
            model_name='factorydetailedaccount',
            constraint=models.UniqueConstraint(fields=('subsidiary', 'code'), name='uniq_factory_detailed_account_code'),
        ),
    ]
