# Generated by Django 6.0.6 on 2026-10-02 04:58

import backend.models.catalog
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_cost_layers(apps, schema_editor):
    Layer = apps.get_model("backend", "InventoryCostLayer")
    for layer in Layer.objects.all().iterator():
        layer.original_qty = layer.qty_remaining
        layer.uuid = uuid.uuid4()
        layer.save(update_fields=["original_qty", "uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_accounting_gateway_phase_one'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(max_length=300, upload_to=backend.models.catalog.document_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('override_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location_kind', models.CharField(choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('released', 'آزادشده'), ('consumed', 'مصرف\u200cشده'), ('cancelled', 'لغوشده')], default='active', max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventorycostlayer',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='cost_layer_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cost_layers', to='backend.branch', to_field='code'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='location_kind',
            field=models.CharField(blank=True, choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='original_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='backend.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='backend.materialsupplier'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='backend.productvariant'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cost_layers', to='backend.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorycostlayer',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='backend.material'),
        ),
        migrations.AlterField(
            model_name='inventorycostlayer',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='backend.inventorytransaction'),
        ),
        migrations.RunPython(backfill_legacy_cost_layers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventorycostlayer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['material', 'location_kind', 'created_at'], name='ix_cost_lot_material'),
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['variant', 'location_kind', 'created_at'], name='ix_cost_lot_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventorycostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('original_qty__gte', 0)), name='ck_cost_layer_original'),
        ),
        migrations.AddConstraint(
            model_name='inventorycostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('qty_remaining__lte', models.F('original_qty'))), name='ck_cost_layer_remaining_original'),
        ),
        migrations.AddConstraint(
            model_name='inventorycostlayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('variant__isnull', True)), models.Q(('material__isnull', True), ('variant__isnull', False)), _connector='OR'), name='ck_cost_layer_one_item'),
        ),
        migrations.AddConstraint(
            model_name='inventorycostlayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('location_kind', ''), ('warehouse__isnull', True)), models.Q(('branch__isnull', True), ('location_kind', 'warehouse'), ('warehouse__isnull', False)), models.Q(('branch__isnull', False), ('location_kind', 'branch'), ('warehouse__isnull', True)), _connector='OR'), name='ck_cost_layer_location'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.journalentry'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.productionorder'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='cost_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='backend.inventorycostlayer'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='backend.material'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consumption', to='backend.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_consumptions', to='backend.salelineitem'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_consumption_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_consumptions', to='backend.productionorder'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_consumptions', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='backend.productvariant'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='consumption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='backend.inventoryconsumption'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.inventoryconsumption'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='reservation_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='backend.branch', to_field='code'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='backend.material'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='backend.salelineitem'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='backend.productionorder'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_inventory_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='backend.productvariant'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='backend.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='backend.inventoryreservation'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.inventoryreservation'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.UniqueConstraint(fields=('consumption', 'cost_layer'), name='uq_consumption_layer'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_allocation_qty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_allocation_cost'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['material', 'status', 'location_kind'], name='ix_reserve_material'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['variant', 'status', 'location_kind'], name='ix_reserve_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_reservation_qty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('variant__isnull', True)), models.Q(('material__isnull', True), ('variant__isnull', False)), _connector='OR'), name='ck_reservation_one_item'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('location_kind', 'warehouse'), ('warehouse__isnull', False)), models.Q(('branch__isnull', False), ('location_kind', 'branch'), ('warehouse__isnull', True)), _connector='OR'), name='ck_reservation_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_consumption_qty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='ck_consumption_cost'),
        ),
        migrations.AddConstraint(
            model_name='inventoryconsumption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('variant__isnull', True)), models.Q(('material__isnull', True), ('variant__isnull', False)), _connector='OR'), name='ck_consumption_one_item'),
        ),
        migrations.AddConstraint(
            model_name='inventoryconsumption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('overridden_by__isnull', True), ('override_reason', '')), models.Q(('overridden_by__isnull', False), models.Q(('override_reason', ''), _negated=True)), _connector='OR'), name='ck_consumption_override_audit'),
        ),
        migrations.AddConstraint(
            model_name='documentattachment',
            constraint=models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='ck_attachment_size'),
        ),
        migrations.AddConstraint(
            model_name='documentattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumption__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', False), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', False)), models.Q(('consumption__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', False), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', False), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('inventory_transaction__isnull', False), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', False), ('sale__isnull', True)), models.Q(('consumption__isnull', False), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), _connector='OR'), name='ck_attachment_one_source'),
        ),
    ]
