# Generated by Django 6.0.6 on 2026-10-02 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_inventory_reservations_lots_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تاییدشده')], db_index=True, default='draft', max_length=16)),
                ('receipt_number', models.CharField(max_length=80)),
                ('invoice_number', models.CharField(max_length=80)),
                ('is_final', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('ordered_unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('received_unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('quantity', 'مقدار'), ('price', 'قیمت')], max_length=16)),
                ('expected_value', models.DecimalField(decimal_places=3, max_digits=18)),
                ('actual_value', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('approved', 'تاییدشده'), ('partial', 'تحویل ناقص'), ('received', 'تحویل کامل'), ('cancelled', 'لغوشده')], db_index=True, default='approved', max_length=16)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('destination_kind', models.CharField(choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تاییدشده'), ('ordered', 'سفارش\u200cگذاری\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='draft', max_length=16)),
                ('destination_kind', models.CharField(choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('source_type', models.CharField(max_length=40)),
                ('source_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='documentattachment',
            name='ck_attachment_one_source',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='accounting_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt', to='backend.financialevent'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt', to='backend.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='backend.goodsreceipt'),
        ),
        migrations.AddConstraint(
            model_name='documentattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumption__isnull', True), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', False), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', False)), models.Q(('consumption__isnull', True), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', False), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', False), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', False), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', False), ('sale__isnull', True)), models.Q(('consumption__isnull', False), ('goods_receipt__isnull', True), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), models.Q(('consumption__isnull', True), ('goods_receipt__isnull', False), ('inventory_transaction__isnull', True), ('journal__isnull', True), ('production_order__isnull', True), ('purchase_invoice__isnull', True), ('reservation__isnull', True), ('sale__isnull', True)), _connector='OR'), name='ck_attachment_one_source'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='inventory_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_line', to='backend.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='backend.material'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='procurementadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementadjustment',
            name='receipt_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='backend.goodsreceiptline'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='purchase_order_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='backend.branch', to_field='code'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='backend.materialsupplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='backend.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='backend.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='backend.material'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='backend.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='purchase_request_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='backend.branch', to_field='code'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='backend.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='backend.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='backend.material'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='backend.salelineitem'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='backend.productionorder'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='request_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_line', to='backend.purchaserequestline'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('order', 'receipt_number'), name='uq_order_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('order', 'invoice_number'), name='uq_order_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'order_line'), name='uq_receipt_order_line'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gt', 0)), name='ck_receipt_expected_qty'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gt', 0)), name='ck_receipt_received_qty'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('received_unit_price__gte', 0)), name='ck_receipt_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('destination_kind', 'warehouse'), ('warehouse__isnull', False)), models.Q(('branch__isnull', False), ('destination_kind', 'branch'), ('warehouse__isnull', True)), _connector='OR'), name='ck_purchase_request_location'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('destination_kind', 'warehouse'), ('warehouse__isnull', False)), models.Q(('branch__isnull', False), ('destination_kind', 'branch'), ('warehouse__isnull', True)), _connector='OR'), name='ck_purchase_order_location'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_key', 'material'), name='uq_shortage_source_material'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_purchase_request_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__gt', 0)), name='ck_purchase_order_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='ck_purchase_order_received_qty'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_purchase_order_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('ordered_quantity'))), name='ck_purchase_order_remaining'),
        ),
    ]
