# Generated by Django 6.0.6 on 2026-10-02 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_unified_procurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('released', 'آزادشده'), ('executed', 'اجراشده'), ('cancelled', 'لغوشده')], db_index=True, default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fulfillment_plans', to=settings.AUTH_USER_MODEL)),
                ('sale_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan', to='backend.salelineitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fulfillment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sale_line_id'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('route_kind', models.CharField(choices=[('branch_stock', 'موجودی شعبه'), ('warehouse_stock', 'موجودی انبار'), ('factory', 'تولید کارخانه'), ('merchant', 'خرید بازرگان')], db_index=True, max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('source_location_kind', models.CharField(blank=True, choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], default='', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('reserved', 'رزروشده'), ('blocked', 'دارای کسری'), ('released', 'آزادشده'), ('executed', 'اجراشده'), ('cancelled', 'لغوشده')], db_index=True, default='planned', max_length=16)),
                ('bom_snapshot', models.JSONField(blank=True, default=list)),
                ('shortage_snapshot', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.fulfillmentplan')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan_lines', to='backend.productionorder')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan_line', to='backend.inventoryreservation')),
                ('shortage_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan_lines', to='backend.purchaserequest')),
                ('source_branch', models.ForeignKey(blank=True, db_column='fulfillment_source_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan_lines', to='backend.branch', to_field='code')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan_lines', to='backend.warehouse')),
            ],
            options={
                'ordering': ['plan_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MerchantSupplyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('destination_kind', models.CharField(choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'باز'), ('ordered', 'سفارش\u200cشده'), ('received', 'تحویل\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, db_column='merchant_demand_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_supply_demands', to='backend.branch', to_field='code')),
                ('plan_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_demand', to='backend.fulfillmentplanline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_supply_demands', to='backend.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_supply_demands', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_supply_demands', to='backend.productvariant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_supply_demands', to='backend.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('source_kind', models.CharField(choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], max_length=16)),
                ('destination_kind', models.CharField(choices=[('warehouse', 'انبار'), ('branch', 'شعبه')], max_length=16)),
                ('status', models.CharField(choices=[('in_transit', 'در مسیر'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='in_transit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer', to='backend.financialevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(blank=True, db_column='stock_transfer_destination_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backend.branch', to_field='code')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backend.warehouse')),
                ('issue_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_issue', to='backend.inventorytransaction')),
                ('plan_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='backend.fulfillmentplanline')),
                ('receipt_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_receipt', to='backend.inventorytransaction')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(blank=True, db_column='stock_transfer_source_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backend.branch', to_field='code')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backend.warehouse')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='backend.productvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fulfillmentplanline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_fulfillment_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentplanline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('route_kind', 'branch_stock'), ('source_branch__isnull', False), ('source_location_kind', 'branch'), ('source_warehouse__isnull', True)), models.Q(('route_kind', 'warehouse_stock'), ('source_branch__isnull', True), ('source_location_kind', 'warehouse'), ('source_warehouse__isnull', False)), models.Q(('route_kind__in', ['factory', 'merchant']), ('source_branch__isnull', True), ('source_location_kind', ''), ('source_warehouse__isnull', True)), _connector='OR'), name='ck_fulfillment_line_source'),
        ),
        migrations.AddConstraint(
            model_name='merchantsupplydemand',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_merchant_demand_qty'),
        ),
        migrations.AddConstraint(
            model_name='merchantsupplydemand',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('destination_kind', 'warehouse'), ('warehouse__isnull', False)), models.Q(('branch__isnull', False), ('destination_kind', 'branch'), ('warehouse__isnull', True)), _connector='OR'), name='ck_merchant_demand_location'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_stock_transfer_qty'),
        ),
    ]
