# Generated by Django 6.0.6 on 2026-10-02 05:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_legacy_bom_snapshots(apps, schema_editor):
    BOMVersion = apps.get_model("backend", "BOMVersion")
    BOMLine = apps.get_model("backend", "BOMLine")
    FulfillmentPlanLine = apps.get_model("backend", "FulfillmentPlanLine")
    for plan_line in FulfillmentPlanLine.objects.select_related("plan__sale_line").filter(
        bom_version__isnull=True
    ):
        sale_line = plan_line.plan.sale_line
        if not sale_line.product_id or not plan_line.bom_snapshot:
            continue
        latest = (
            BOMVersion.objects.filter(product_id=sale_line.product_id)
            .order_by("-version")
            .values_list("version", flat=True)
            .first()
            or 0
        )
        bom = BOMVersion.objects.create(
            product_id=sale_line.product_id,
            version=latest + 1,
            status="published",
            source_snapshot={"legacy_fulfillment_plan_line_id": plan_line.pk},
            published_at=timezone.now(),
        )
        merged = {}
        for row in plan_line.bom_snapshot:
            material_id = row.get("material_id")
            quantity = row.get("bom_quantity")
            if material_id and quantity:
                merged[material_id] = merged.get(material_id, Decimal("0")) + Decimal(str(quantity))
        for order, (material_id, quantity) in enumerate(merged.items()):
            BOMLine.objects.create(
                bom_version_id=bom.pk,
                material_id=material_id,
                quantity=quantity,
                normal_spoilage_rate=0,
                source_kind="legacy",
                source_reference=f"FulfillmentPlanLine:{plan_line.pk}",
                sort_order=order,
            )
        plan_line.bom_version_id = bom.pk
        plan_line.save(update_fields=["bom_version"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_fulfillment_planning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('retired', 'بازنشسته')], default='draft', max_length=16)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_versions', to='backend.product')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_bom_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('normal_spoilage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('source_kind', models.CharField(choices=[('product', 'محصول'), ('frame', 'کلاف'), ('workset', 'ست'), ('recipe', 'دستور کارگاه'), ('legacy', 'اسنپ\u200cشات قدیمی')], default='product', max_length=16)),
                ('source_reference', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_version_lines', to='backend.material')),
                ('bom_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='backend.bomversion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fulfillmentplanline',
            name='bom_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plan_lines', to='backend.bomversion'),
        ),
        migrations.RunPython(migrate_legacy_bom_snapshots, noop_reverse),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('blocked', 'دارای کسری'), ('released', 'آزادشده'), ('in_progress', 'در جریان'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده')], default='draft', max_length=16)),
                ('overhead_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('actual_material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='backend.bomversion')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_production_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_runs', to=settings.AUTH_USER_MODEL)),
                ('fulfillment_plan_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_run', to='backend.fulfillmentplanline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='backend.product')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_run', to='backend.productionorder')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='backend.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='backend.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='backend.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(choices=[('consumption', 'مصرف'), ('extra_consumption', 'مصرف اضافه'), ('return', 'برگشت'), ('scrap', 'ضایعات'), ('completion', 'تکمیل')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_production_events', to=settings.AUTH_USER_MODEL)),
                ('consumption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_event', to='backend.inventoryconsumption')),
                ('financial_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_event', to='backend.financialevent')),
                ('inventory_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_event', to='backend.inventorytransaction')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_events', to='backend.material')),
                ('original_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='backend.productionevent')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_production_events', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='backend.productionrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('shortage_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='backend.bomline')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_requirements', to='backend.material')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_requirement', to='backend.inventoryreservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='backend.productionrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lot_number', models.CharField(max_length=80, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=0, max_digits=18)),
                ('completed_at', models.DateTimeField()),
                ('cost_layer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_lot', to='backend.inventorycostlayer')),
                ('inventory_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_lot', to='backend.inventorytransaction')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_lot', to='backend.productionrun')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_lots', to='backend.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_lots', to='backend.warehouse')),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='uq_bom_product_version'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.UniqueConstraint(fields=('bom_version', 'material'), name='uq_bom_version_material'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_bom_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('normal_spoilage_rate__gte', 0), ('normal_spoilage_rate__lte', 100)), name='ck_bom_line_spoilage'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_production_run_qty'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('overhead_cost__gte', 0)), name='ck_run_overhead'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('actual_material_cost__gte', 0)), name='ck_run_material_cost'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='ck_run_total_cost'),
        ),
        migrations.AddConstraint(
            model_name='productionevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_production_event_qty'),
        ),
        migrations.AddConstraint(
            model_name='productionevent',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='ck_production_event_cost'),
        ),
        migrations.AddConstraint(
            model_name='materialrequirement',
            constraint=models.UniqueConstraint(fields=('run', 'material'), name='uq_run_requirement_material'),
        ),
        migrations.AddConstraint(
            model_name='materialrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('required_quantity__gt', 0)), name='ck_run_req_qty'),
        ),
        migrations.AddConstraint(
            model_name='materialrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('shortage_quantity__gte', 0)), name='ck_run_shortage'),
        ),
        migrations.AddConstraint(
            model_name='productlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_product_lot_qty'),
        ),
        migrations.AddConstraint(
            model_name='productlot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='ck_product_lot_unit_cost'),
        ),
        migrations.AddConstraint(
            model_name='productlot',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='ck_product_lot_total_cost'),
        ),
    ]
