# Generated by Django 6.0.6 on 2026-10-02 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_production_actual_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت\u200cشده')], default='draft', max_length=16)),
                ('total_actual_cogs', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cogs_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cogs_delivery', to='backend.financialevent')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_deliveries', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_document', to='backend.sale')),
                ('sale_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_delivery', to='backend.financialevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('total_actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumption', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_line', to='backend.inventoryconsumption')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='backend.deliverydocument')),
                ('fulfillment_plan_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_line', to='backend.fulfillmentplanline')),
                ('product_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='backend.productlot')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='backend.salelineitem')),
            ],
            options={
                'ordering': ['sale_line_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت\u200cشده')], default='draft', max_length=16)),
                ('revenue_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total_actual_cogs', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=500)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cogs_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_cogs', to='backend.financialevent')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='backend.deliverydocument')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('revenue_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_revenue', to='backend.financialevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('revenue_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('allocation_snapshot', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='backend.deliveryline')),
                ('inventory_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_line', to='backend.inventorytransaction')),
                ('return_cost_layer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_line', to='backend.inventorycostlayer')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='backend.salesreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='merchantsupplydemand',
            name='receipt_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_supply_demand', to='backend.inventorytransaction'),
        ),
        migrations.AddConstraint(
            model_name='deliverydocument',
            constraint=models.CheckConstraint(condition=models.Q(('total_actual_cogs__gte', 0)), name='ck_delivery_cogs'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_delivery_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('total_actual_cost__gte', 0)), name='ck_delivery_line_cost'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_amount__gte', 0)), name='ck_return_revenue'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='ck_return_vat'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(condition=models.Q(('total_actual_cogs__gte', 0)), name='ck_return_cogs'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnline',
            constraint=models.UniqueConstraint(fields=('sales_return', 'delivery_line'), name='uq_return_delivery_line'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_return_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost__gte', 0)), name='ck_return_line_cost'),
        ),
    ]
