"""داده‌های اولیه سیستم — فقط برای seed در MySQL؛ runtime از DB خوانده می‌شود."""

# (category, code, label, sort_order, meta)
FACTORY_AND_SYSTEM_LOOKUPS = [
    # فروش و اداری
    ("accounting_mode", "automatic", "خودکار — ثبت در حساب متناسب با روش پرداخت", 0, {}),
    ("accounting_mode", "manual", "دستی — فقط ارسال اطلاعات به اداری", 1, {}),
    ("discount_type", "cashback", "کش‌بک", 3, {}),
    ("order_status", "final_approved", "تایید نهایی", 3, {"color": "#10b981"}),
    ("attendance_status", "mission", "ماموریت", 3, {}),
    ("fulfillment_route", "factory", "کارخانه", 0, {}),
    ("fulfillment_route", "warehouse", "انبار", 1, {}),
    ("fulfillment_route", "customer_pickup", "تحویل به مشتری", 2, {}),
    ("fulfillment_route", "merchant", "بازرگان", 3, {}),
    ("receive_kind", "customer", "مشتری", 0, {}),
    ("receive_kind", "branch_floor", "کف شعبه", 1, {}),
    ("receive_kind", "warehouse", "انبار", 2, {}),
    ("receive_kind", "merchant", "بازرگان", 3, {}),
    ("receive_kind", "repair", "تعمیر", 4, {}),
    ("stock_source", "warehouse", "انبار", 0, {}),
    ("stock_source", "branch", "شعبه", 1, {}),
    ("document_code", "1", "۱ - سند افتتاحیه", 0, {}),
    ("document_code", "2", "۲ - سند عملیاتی", 1, {}),
    ("document_code", "3", "۳ - سند انتقالی", 2, {}),
    ("document_code", "4", "۴ - سند اصلاحیه", 3, {}),
    ("material_unit", "متر", "متر", 0, {}),
    ("material_unit", "لیتر", "لیتر", 1, {}),
    ("material_unit", "گالن", "گالن", 2, {}),
    ("material_unit", "عدد", "عدد", 3, {}),
    ("material_unit", "کیلوگرم", "کیلوگرم", 4, {}),
    ("material_unit", "ورق", "ورق", 5, {}),
    ("material_unit", "قوطی", "قوطی", 6, {}),
    ("material_unit", "حلب", "حلب", 7, {}),
    ("account_class", "asset", "دارایی", 0, {}),
    ("account_class", "liability", "بدهی", 1, {}),
    ("account_class", "equity", "سرمایه", 2, {}),
    ("account_class", "revenue", "درآمد", 3, {}),
    ("account_class", "expense", "هزینه", 4, {}),
    ("normal_balance", "debit", "بدهکار", 0, {}),
    ("normal_balance", "credit", "بستانکار", 1, {}),
    ("source_module", "sales", "فروش", 0, {}),
    ("source_module", "warehouse", "انبار", 1, {}),
    ("source_module", "factory", "کارخانه", 2, {}),
    ("source_module", "manual", "دستی", 3, {}),
    ("build_model", "frame_line", "خط کلاف", 0, {}),
    ("pipeline_end", "upholstery", "رویه‌کوبی", 0, {}),
    ("pipeline_end", "assembly", "مونتاژ", 1, {}),
    ("location_kind", "warehouse", "انبار", 0, {}),
    ("location_kind", "branch", "شعبه", 1, {}),
    ("fabric_issue_status", "pending", "در انتظار", 0, {"color": "#f59e0b"}),
    ("fabric_issue_status", "reserved", "رزرو شده", 1, {"color": "#6366f1"}),
    ("fabric_issue_status", "issued", "تحویل شده", 2, {"color": "#10b981"}),
    # کلاف و مبلمان
    ("frame_design_style", "modern", "مدرن", 0, {}),
    ("frame_design_style", "classic", "کلاسیک", 1, {}),
    ("frame_design_style", "neo_classic", "نیو کلاسیک", 2, {}),
    ("frame_design_style", "minimal", "مینیمال", 3, {}),
    ("frame_design_style", "avant_garde", "اوانگارد", 4, {}),
    ("frame_wood_type", "ash_georgian_g1", "راش گرجستان درجه ۱", 0, {}),
    ("frame_wood_type", "oak", "بلوط", 1, {}),
    ("frame_wood_type", "walnut", "گردو", 2, {}),
    ("frame_wood_type", "russian", "روس", 3, {}),
    ("frame_wood_type", "tusca", "توسکا", 4, {}),
    ("frame_wood_type", "ash_russian_mix", "ترکیب راش و روس", 5, {}),
    ("frame_arm_style", "none", "بدون دسته", 0, {}),
    ("frame_arm_style", "one", "تک‌دسته", 1, {}),
    ("frame_arm_style", "two", "دو دسته", 2, {}),
    ("frame_arm_style", "one_left", "تک‌دسته چپ", 3, {}),
    ("frame_arm_style", "one_right", "تک‌دسته راست", 4, {}),
    ("frame_piece_kind", "armchair", "مبل تک", 0, {"allowed_arms": ["none", "one", "two"], "seat_count": 1}),
    ("frame_piece_kind", "sofa_2", "کاناپه ۲ نفره", 1, {"allowed_arms": ["one_left", "one_right", "two"], "seat_count": 2}),
    ("frame_piece_kind", "sofa_3", "کاناپه ۳ نفره", 2, {"allowed_arms": ["one_left", "one_right", "two"], "seat_count": 3}),
    ("frame_piece_kind", "sofa_4", "کاناپه ۴ نفره", 3, {"allowed_arms": ["one_left", "one_right", "two"], "seat_count": 4}),
    ("frame_piece_kind", "sofa_5", "کاناپه ۵ نفره", 4, {"allowed_arms": ["one_left", "one_right", "two"], "seat_count": 5}),
    ("frame_piece_kind", "chaise", "شزلون", 5, {"allowed_arms": ["one_left", "one_right"], "seat_count": 1}),
    ("frame_piece_kind", "pouf", "پاف", 6, {"allowed_arms": ["none"], "seat_count": 1}),
    ("frame_piece_kind", "bench", "بنچ", 7, {"allowed_arms": ["none"], "seat_count": 1}),
    ("frame_piece_kind", "loveseat", "لاو ست", 8, {"allowed_arms": ["none"], "seat_count": 2}),
    ("frame_piece_kind", "side_table", "کنار مبلی", 9, {"allowed_arms": ["none"], "seat_count": 0, "assembly_only": True}),
    ("frame_piece_kind", "coffee_table", "جلو مبلی", 10, {"allowed_arms": ["none"], "seat_count": 0, "assembly_only": True}),
    ("frame_component_type", "three_seater", "کاناپه ۳ نفره", 0, {"default_quantity": 1}),
    ("frame_component_type", "armchair", "مبل تک‌نفره", 1, {"default_quantity": 2}),
    ("frame_component_type", "side_table", "کنار مبل", 2, {"default_quantity": 2}),
    ("frame_component_type", "coffee_table", "جلو مبل", 3, {"default_quantity": 1}),
    ("frame_rule_key", "back_fabric", "پشت پارچه", 0, {}),
    ("frame_rule_key", "back_wood", "پشت چوب", 1, {}),
    ("frame_rule_key", "extra", "متریال اضافه", 2, {}),
    ("frame_unit", "متر", "متر", 0, {}),
    ("frame_unit", "عدد", "عدد", 1, {}),
    # دستور کارگاه
    ("workshop_recipe_kind", "paint", "رنگ", 0, {}),
    ("workshop_recipe_kind", "fabric", "پارچه", 1, {}),
    ("workshop_recipe_kind", "foam", "اسفنج", 2, {}),
    ("workshop_recipe_kind", "cushion", "کوسن", 3, {}),
    ("workshop_recipe_kind", "webbing", "تسمه", 4, {}),
    ("workshop_paint_category", "thinner", "تینر", 0, {}),
    ("workshop_paint_category", "paint", "رنگ و پلی‌استر", 1, {}),
    ("workshop_paint_category", "putty", "بتونه و سیلر", 2, {}),
    ("workshop_paint_category", "patina", "پتینه و ورق طلا", 3, {}),
    ("workshop_paint_category", "abrasive", "سنباده و ابزار مصرفی", 4, {}),
    ("workshop_paint_category", "chemical", "هاردنر و شیمیایی", 5, {}),
    ("workshop_fabric_category", "velvet_plain", "مخمل ساده", 0, {}),
    ("workshop_fabric_category", "velvet_pattern", "مخمل طرح‌دار", 1, {}),
    ("workshop_fabric_category", "washed_cotton", "کتان شست", 2, {}),
    ("workshop_fabric_category", "heavy_linen", "لینن ضخیم", 3, {}),
    ("workshop_fabric_category", "matte_leather", "چرم مصنوعی مات", 4, {}),
    ("workshop_fabric_category", "soft_suede", "جیر نرم", 5, {}),
    ("workshop_fabric_category", "loop_weave", "بافت حلقه‌ای", 6, {}),
    ("workshop_fabric_category", "stretch_cloth", "پارچه کشسان", 7, {}),
    ("workshop_fabric_category", "matte_satin", "ساتن مات", 8, {}),
    ("workshop_fabric_category", "outdoor_cloth", "پارچه فضای باز", 9, {}),
    ("workshop_fabric_company", "nura_weave", "بافندگی نورا", 0, {}),
    ("workshop_fabric_company", "aria_textile", "منسوجات آریا", 1, {}),
    ("workshop_fabric_company", "sepehr_hide", "چرمینه سپهر", 2, {}),
    ("workshop_fabric_company", "roshan_line", "کالکشن روشان", 3, {}),
    ("workshop_fabric_country", "ایران", "ایران", 0, {}),
    ("workshop_fabric_country", "ترکیه", "ترکیه", 1, {}),
    ("workshop_fabric_country", "چین", "چین", 2, {}),
    ("workshop_fabric_country", "ایتالیا", "ایتالیا", 3, {}),
    ("workshop_fabric_country", "هند", "هند", 4, {}),
    ("workshop_fabric_country", "اسپانیا", "اسپانیا", 5, {}),
]

# meta روی payment_method برای نگاشت حساب
PAYMENT_METHOD_ACCOUNT_META = {
    "cash": {"account_slug": "cash_documents"},
    "check": {"account_slug": "collection_at_bank"},
    "card": {"account_slug": "bank"},
    "transfer": {"account_slug": "bank"},
}

JOURNAL_ENTRY_TYPE_ACCOUNT_META = {
    "sale": {"account_slug": "product_sales"},
    "receivable": {"account_slug": "receivables"},
    "payment": {"account_slug": "bank"},
    "refund": {"account_slug": "raw_materials_purchase_return"},
    "adjustment": {"account_slug": "admin_overhead"},
    "other": {"account_slug": "other_revenue"},
    "manual": {"account_slug": "other_revenue"},
}

CHART_VERSION = "1.0.0"

# This maps imported Excel codes to application roles. It is not a chart of
# accounts and never creates database rows; account names and hierarchy always
# come from the uploaded workbook.
ACCOUNT_ROLE_BY_CODE = {
    "1120": "cash_documents",
    "1130": "petty_cash",
    "1210": "bank",
    "1220": "collection_at_bank",
    "1310": "receivables",
    "1320": "other_receivables",
    "1330": "vat_receivable",
    "1510": "raw_materials_inventory",
    "1520": "wip_inventory",
    "1530": "semi_finished_inventory",
    "1540": "finished_goods_inventory",
    "1710": "prepayments",
    "1740": "investment_projects",
    "1750": "deposits_sureties",
    "4110": "bank_payables",
    "4311": "accounts_payable",
    "4321": "other_payables",
    "4330": "vat_payable",
    "5110": "long_term_loans",
    "6320": "retained_earnings",
    "7210": "raw_materials_sales",
    "7230": "semi_finished_sales",
    "7240": "product_sales",
    "7250": "sales_allowances",
    "7510": "other_revenue",
    "7520": "purchase_discount",
    "8110": "production_payroll",
    "8111": "production_overhead",
    "8112": "cogs",
    "8210": "admin_payroll",
    "8211": "admin_overhead",
    "8220": "distribution_sales_expense",
    "8310": "financial_expense",
    "9430": "raw_materials_purchase_return",
    "9710": "memorandum_accounts",
    "9720": "memorandum_counterpart",
    "9930": "raw_materials_purchase_return_cogs",
}

POSTING_RULES = {
    "sale": [
        {"side": "credit", "slug": "product_sales", "amount_key": "final_amount"},
        {"side": "debit", "slug": "receivables", "amount_key": "outstanding", "min_amount": True},
        {"side": "debit", "account_key": "payment_account", "amount_key": "paid", "min_amount": True},
    ],
    "payment": [
        {"side": "debit", "account_key": "payment_account", "amount_key": "amount"},
        {"side": "credit", "slug": "receivables", "amount_key": "amount"},
    ],
    "check_register": [
        {"side": "debit", "account_key": "registration_account", "amount_key": "amount"},
        {"side": "credit", "slug": "receivables", "amount_key": "amount"},
    ],
    "check_clear": [
        {"side": "debit", "account_key": "deposit_account", "amount_key": "amount"},
        {"side": "credit", "account_key": "registration_account", "amount_key": "amount"},
    ],
    "material_receipt": [
        {"side": "debit", "slug": "raw_materials_inventory", "amount_key": "value"},
        {"side": "credit", "slug": "accounts_payable", "amount_key": "value"},
    ],
    "material_consumption": [
        {"side": "debit", "slug": "wip_inventory", "amount_key": "cost"},
        {"side": "credit", "slug": "raw_materials_inventory", "amount_key": "cost"},
    ],
    "material_consumption_reverse": [
        {"side": "debit", "slug": "raw_materials_inventory", "amount_key": "cost"},
        {"side": "credit", "slug": "wip_inventory", "amount_key": "cost"},
    ],
    "goods_sale_issue": [
        {"side": "debit", "slug": "cogs", "amount_key": "cost"},
        {"side": "credit", "slug": "finished_goods_inventory", "amount_key": "cost"},
    ],
    "goods_sale_issue_reverse": [
        {"side": "debit", "slug": "finished_goods_inventory", "amount_key": "cost"},
        {"side": "credit", "slug": "cogs", "amount_key": "cost"},
    ],
}

CODE_PREFIX_TO_CLASS = {
    "1": "asset",
    "4": "liability",
    "5": "liability",
    "6": "equity",
    "7": "revenue",
    "8": "expense",
    "9": "expense",
}
