"""تمام endpointهای API پروژه — پیشوند «/api/» در backend/urls.py."""

from django.urls import path

from api.views import books as accounting_books
from api.views import statements as accounting_statements
from api.views import trade as accounting_trade
from api.views import payables as accounting_payables
from api.views import accounting_controls
from api.views import (
    accounting,
    attendance,
    audit_logs,
    auth,
    birthday_sms,
    config,
    customers,
    cycle,
    dashboard,
    accounting_modules,
    factory_accounting,
    factory_orders,
    frames,
    furniture_worksets,
    beta_workshops,
    installments,
    loyalty_levels,
    materials,
    notifications,
    office_forms,
    office_orders,
    org_chart,
    products,
    record_filter,
    workshop_recipes,
    reminder_sms,
    role_definitions,
    rfm,
    sales,
    sms,
    sms_club,
    staff,
    wallet,
)

urlpatterns = [
    # --- Auth (/api/auth/) ---
    path("auth/login/", auth.login, name="auth-login"),
    path("auth/logout/", auth.logout, name="auth-logout"),
    path("auth/me/", auth.me, name="auth-me"),
    path("auth/roles/", auth.role_list, name="auth-roles"),
    path("auth/users/", auth.user_list, name="auth-users"),
    path("auth/users/<int:pk>/", auth.user_detail, name="auth-user-detail"),
    path("auth/users/<int:pk>/assign-department/", auth.user_assign_department, name="auth-user-assign-department"),
    path("auth/users/<int:pk>/reset-password/", auth.user_reset_password, name="auth-user-reset-password"),
    path("auth/users/<int:pk>/deactivate/", auth.user_deactivate, name="auth-user-deactivate"),
    path("auth/assign-role/", auth.assign_role, name="auth-assign-role"),
    path("auth/change-password/", auth.change_password, name="auth-change-password"),
    path("auth/reset-business-data/", auth.reset_business_data, name="auth-reset-business-data"),
    path("auth/permissions/", role_definitions.permission_matrix, name="auth-permissions"),
    path("auth/role-definitions/", role_definitions.role_definition_list, name="auth-role-definitions"),
    path(
        "auth/role-definitions/<slug:slug>/",
        role_definitions.role_definition_detail,
        name="auth-role-definition-detail",
    ),
    path("auth/org-ranks/", role_definitions.org_rank_list, name="auth-org-ranks"),
    path("auth/org-ranks/<int:pk>/", role_definitions.org_rank_detail, name="auth-org-rank-detail"),
    path("config/", config.app_config, name="app-config"),
    path("config/branches/", config.branch_list, name="config-branches"),
    path("config/branches/<int:pk>/", config.branch_detail, name="config-branch-detail"),
    path("config/lookups/", config.lookup_list, name="config-lookups"),
    path("config/lookups/<int:pk>/", config.lookup_detail, name="config-lookup-detail"),
    path("config/menu-sections/", config.menu_section_list, name="config-menu-sections"),
    path("config/menu-sections/<int:pk>/", config.menu_section_detail, name="config-menu-section-detail"),
    path("config/page-guides/<slug:code>/", config.page_guide_detail, name="config-page-guide-detail"),
    path("config/branding/logo/", config.branding_logo, name="config-branding-logo"),
    path("config/attendance-settings/", config.attendance_settings, name="config-attendance-settings"),
    path("config/ranking-settings/", config.ranking_settings, name="config-ranking-settings"),
    path("config/inventory-settings/", config.inventory_settings, name="config-inventory-settings"),
    path("config/ticket-grades/", config.ticket_grades, name="config-ticket-grades"),
    path("org-chart/", org_chart.org_chart, name="org-chart"),
    path("org-chart/reassign/", org_chart.org_chart_reassign, name="org-chart-reassign"),

    # --- Dashboard ---
    path("dashboard/summary/", dashboard.dashboard_summary, name="dashboard-summary"),

    # --- Customers ---
    path("customers/", customers.customer_list, name="customer-list"),
    path(
        "customers/recalculate-all-levels/",
        customers.recalculate_all_levels,
        name="customer-recalculate-all",
    ),
    path("customers/top-buyers/", customers.customer_top_buyers, name="customer-top-buyers"),
    path("customers/<int:pk>/", customers.customer_detail, name="customer-detail"),
    path(
        "customers/<int:pk>/recalculate-level/",
        customers.recalculate_level,
        name="customer-recalculate-level",
    ),
    path(
        "customers/<int:pk>/history/",
        customers.customer_history,
        name="customer-history",
    ),
    path("customers/import/", customers.customer_import, name="customer-import"),
    path("customers/export/", customers.customer_export, name="customer-export"),
    path(
        "customers/<int:pk>/wallet/",
        wallet.customer_wallet,
        name="customer-wallet",
    ),

    # --- Sales ---
    path("sales/reports/daily/", sales.sales_daily_report, name="sales-daily-report"),
    path("sales/reports/weekly/", sales.sales_weekly_report, name="sales-weekly-report"),
    path("sales/reports/monthly/", sales.sales_monthly_report, name="sales-monthly-report"),
    path("sales/reports/daily-breakdown/", sales.sales_daily_breakdown, name="sales-daily-breakdown"),
    path("sales/reports/yearly/", sales.sales_yearly_report, name="sales-yearly-report"),
    path("sales/employee-ranking/", sales.employee_ranking, name="sales-employee-ranking"),
    path("sales/", sales.sale_list, name="sale-list"),
    path("sales/<int:pk>/approve-branch/", sales.sale_approve_branch, name="sale-approve-branch"),
    path("sales/<int:pk>/approve-accounting/", sales.sale_approve_accounting, name="sale-approve-accounting"),
    path("sales/<int:pk>/journals/", sales.sale_journals, name="sale-journals"),
    path("sales/<int:pk>/finalize/", sales.sale_finalize, name="sale-finalize"),
    path("sales/<int:pk>/factory-receive/", sales.sale_factory_receive, name="sale-factory-receive"),
    path("sales/<int:pk>/factory-complete/", sales.sale_factory_complete, name="sale-factory-complete"),
    path("sales/<int:pk>/freight-receive/", sales.sale_freight_receive, name="sale-freight-receive"),
    path("sales/<int:pk>/freight-complete/", sales.sale_freight_complete, name="sale-freight-complete"),
    path("sales/<int:pk>/warehouse-complete/", sales.sale_warehouse_complete, name="sale-warehouse-complete"),
    path("sales/<int:pk>/pickup-complete/", sales.sale_pickup_complete, name="sale-pickup-complete"),
    path("sales/<int:pk>/record-payment/",
        sales.sale_record_payment,
        name="sale-record-payment",
    ),
    path("sales/<int:pk>/confirm/", sales.sale_confirm, name="sale-confirm"),
    path("sales/<int:pk>/cancel/", sales.sale_cancel, name="sale-cancel"),
    path("sales/<int:pk>/export-excel/", sales.sale_export_excel, name="sale-export-excel"),
    path("sales/<int:pk>/", sales.sale_detail, name="sale-detail"),

    # --- Office queue (جدول جدا) ---
    path("office/orders/", office_orders.office_order_list, name="office-order-list"),
    path("office/orders/<int:pk>/", office_orders.office_order_detail, name="office-order-detail"),
    path("office/orders/<int:pk>/approve/", office_orders.office_order_approve, name="office-order-approve"),
    path("office/orders/<int:pk>/reject/", office_orders.office_order_reject, name="office-order-reject"),
    path("office/orders/<int:pk>/rollback/", office_orders.office_order_rollback, name="office-order-rollback"),
    path("office/factory-work/", office_orders.office_factory_work_create, name="office-factory-work-create"),

    path("cycle/", cycle.cycle_config, name="cycle-config"),
    path("cycle/me/", cycle.cycle_me, name="cycle-me"),
    path("cycle/warehouses/", cycle.warehouse_list, name="cycle-warehouses"),
    path("cycle/warehouses/<int:pk>/", cycle.warehouse_detail, name="cycle-warehouse-detail"),
    path("cycle/watch/", cycle.cycle_watch, name="cycle-watch"),
    path("cycle/warehouse-orders/", cycle.cycle_warehouse_orders, name="cycle-warehouse-orders"),
    path("cycle/pickup-orders/", cycle.cycle_pickup_orders, name="cycle-pickup-orders"),

    # --- Factory queue (جدول جدا) ---
    path("factory/orders/", factory_orders.factory_order_list, name="factory-order-list"),
    path("factory/orders/<int:pk>/", factory_orders.factory_order_detail, name="factory-order-detail"),
    path("factory/orders/<int:pk>/receive/", factory_orders.factory_order_receive, name="factory-order-receive"),
    path("factory/orders/<int:pk>/complete/", factory_orders.factory_order_complete, name="factory-order-complete"),
    path(
        "factory/orders/<int:pk>/confirm-ready/",
        factory_orders.factory_order_confirm_ready,
        name="factory-order-confirm-ready",
    ),
    path(
        "factory/orders/<int:pk>/send-to-freight/",
        factory_orders.factory_order_send_to_freight,
        name="factory-order-send-to-freight",
    ),
    path(
        "factory/orders/<int:pk>/early-ship-date/",
        factory_orders.factory_order_early_ship_date,
        name="factory-order-early-ship-date",
    ),
    path(
        "factory/orders/<int:pk>/freight-receive/",
        factory_orders.factory_order_freight_receive,
        name="factory-order-freight-receive",
    ),
    path(
        "factory/orders/<int:pk>/freight-complete/",
        factory_orders.factory_order_freight_complete,
        name="factory-order-freight-complete",
    ),

    # --- Installments & Checks ---
    path("installments/", installments.installment_list, name="installment-list"),
    path("installments/export-excel/", installments.installments_export_excel, name="installments-export-excel"),
    path("installments/checks-report/", installments.checks_monthly_report, name="checks-report"),
    path("installments/<int:pk>/pay/", installments.installment_pay, name="installment-pay"),
    path("installments/<int:pk>/", installments.installment_detail, name="installment-detail"),

    # --- Attendance ---
    # --- Products ---
    path("products/categories/", products.category_list, name="product-category-list"),
    path("products/categories/<int:pk>/", products.category_detail, name="product-category-detail"),
    path("products/top-selling/", products.product_top_selling, name="product-top-selling"),
    path("products/stock-transfer/", products.product_stock_transfer, name="product-stock-transfer"),
    path("products/", products.product_list, name="product-list"),
    path("products/<int:pk>/", products.product_detail, name="product-detail"),
    path("materials/reports/", materials.material_reports, name="material-reports"),
    path("materials/stocktakes/", materials.material_stocktake_list, name="material-stocktake-list"),
    path("materials/stocktakes/<int:pk>/", materials.material_stocktake_detail, name="material-stocktake-detail"),
    path("materials/stocktakes/<int:pk>/close/", materials.material_stocktake_close, name="material-stocktake-close"),
    path("materials/", materials.material_list, name="material-list"),
    path("materials/<int:pk>/", materials.material_detail, name="material-detail"),
    path("materials/<int:pk>/approve/", materials.material_approve, name="material-approve"),
    path("materials/<int:pk>/reject/", materials.material_reject, name="material-reject"),
    path("frames/options/", frames.frame_options, name="frame-options"),
    path("frames/", frames.frame_list, name="frame-list"),
    path("frames/<int:pk>/", frames.frame_detail, name="frame-detail"),
    path("frames/<int:pk>/requirements-preview/", frames.frame_requirements_preview, name="frame-requirements-preview"),
    path("frames/<int:pk>/create-product/", frames.frame_create_product, name="frame-create-product"),
    path("furniture-worksets/options/", furniture_worksets.workset_options, name="furniture-workset-options"),
    path("furniture-worksets/", furniture_worksets.workset_list, name="furniture-workset-list"),
    path("furniture-worksets/<int:pk>/", furniture_worksets.workset_detail, name="furniture-workset-detail"),
    path("furniture-worksets/<int:pk>/products/", furniture_worksets.workset_products, name="furniture-workset-products"),

    # --- واحدهای کارگاهی بتا ---
    path("beta/carpentry/stats/", beta_workshops.carpentry_stats, name="beta-carpentry-stats"),
    path("beta/carpentry/sources/", beta_workshops.carpentry_sources, name="beta-carpentry-sources"),
    path("beta/carpentry/workshops/", beta_workshops.carpentry_workshop_list, name="beta-carpentry-workshop-list"),
    path("beta/carpentry/workshops/<int:pk>/", beta_workshops.carpentry_workshop_detail, name="beta-carpentry-workshop-detail"),
    path("beta/carpentry/orders/", beta_workshops.carpentry_order_list, name="beta-carpentry-order-list"),
    path("beta/carpentry/orders/<int:pk>/", beta_workshops.carpentry_order_detail, name="beta-carpentry-order-detail"),
    path("beta/carpentry/tools/", beta_workshops.carpentry_tool_list, name="beta-carpentry-tool-list"),
    path("beta/carpentry/tools/<int:pk>/", beta_workshops.carpentry_tool_detail, name="beta-carpentry-tool-detail"),
    path("beta/carpentry/wood-purchases/", beta_workshops.carpentry_wood_list, name="beta-carpentry-wood-list"),
    path("beta/carpentry/wood-purchases/<int:pk>/", beta_workshops.carpentry_wood_detail, name="beta-carpentry-wood-detail"),
    path("beta/carpentry/services/", beta_workshops.carpentry_service_list, name="beta-carpentry-service-list"),
    path("beta/carpentry/services/<int:pk>/", beta_workshops.carpentry_service_detail, name="beta-carpentry-service-detail"),
    path("beta/carpentry/freight/", beta_workshops.carpentry_freight_list, name="beta-carpentry-freight-list"),
    path("beta/carpentry/freight/<int:pk>/", beta_workshops.carpentry_freight_detail, name="beta-carpentry-freight-detail"),
    path("beta/carpentry/attendance/", beta_workshops.carpentry_attendance_list, name="beta-carpentry-attendance-list"),
    path("beta/carpentry/attendance/<int:pk>/", beta_workshops.carpentry_attendance_detail, name="beta-carpentry-attendance-detail"),
    path("beta/paint/stats/", beta_workshops.paint_stats, name="beta-paint-stats"),
    path("beta/paint/orders/", beta_workshops.paint_order_list, name="beta-paint-order-list"),
    path("beta/paint/orders/<int:pk>/", beta_workshops.paint_order_detail, name="beta-paint-order-detail"),
    path("beta/paint/orders/<int:pk>/advance/", beta_workshops.paint_order_advance, name="beta-paint-order-advance"),
    path("beta/upholstery/stats/", beta_workshops.upholstery_stats, name="beta-upholstery-stats"),
    path("beta/upholstery/jobs/", beta_workshops.upholstery_job_list, name="beta-upholstery-job-list"),
    path("beta/upholstery/jobs/<int:pk>/", beta_workshops.upholstery_job_detail, name="beta-upholstery-job-detail"),
    path("beta/upholstery/jobs/<int:pk>/advance/", beta_workshops.upholstery_job_advance, name="beta-upholstery-job-advance"),
    path("beta/fabric/stats/", beta_workshops.fabric_stats, name="beta-fabric-stats"),
    path("beta/fabric/rolls/", beta_workshops.fabric_roll_list, name="beta-fabric-roll-list"),
    path("beta/fabric/rolls/<int:pk>/", beta_workshops.fabric_roll_detail, name="beta-fabric-roll-detail"),
    path("beta/fabric/dispatches/", beta_workshops.fabric_dispatch_list, name="beta-fabric-dispatch-list"),
    path("beta/qc/stats/", beta_workshops.qc_stats, name="beta-qc-stats"),
    path("beta/qc/inspections/", beta_workshops.qc_inspection_list, name="beta-qc-inspection-list"),
    path("beta/qc/inspections/<int:pk>/", beta_workshops.qc_inspection_detail, name="beta-qc-inspection-detail"),
    path("beta/qc/inspections/<int:pk>/evaluate/", beta_workshops.qc_inspection_evaluate, name="beta-qc-inspection-evaluate"),
    path("beta/foam/stats/", beta_workshops.foam_stats, name="beta-foam-stats"),
    path("beta/foam/jobs/", beta_workshops.foam_job_list, name="beta-foam-job-list"),
    path("beta/foam/jobs/<int:pk>/", beta_workshops.foam_job_detail, name="beta-foam-job-detail"),
    path("beta/foam/jobs/<int:pk>/advance/", beta_workshops.foam_job_advance, name="beta-foam-job-advance"),
    path("beta/cushion/stats/", beta_workshops.cushion_stats, name="beta-cushion-stats"),
    path("beta/cushion/jobs/", beta_workshops.cushion_job_list, name="beta-cushion-job-list"),
    path("beta/cushion/jobs/<int:pk>/", beta_workshops.cushion_job_detail, name="beta-cushion-job-detail"),
    path("beta/cushion/jobs/<int:pk>/advance/", beta_workshops.cushion_job_advance, name="beta-cushion-job-advance"),
    path("beta/assembly/stats/", beta_workshops.assembly_stats, name="beta-assembly-stats"),
    path("beta/assembly/jobs/", beta_workshops.assembly_job_list, name="beta-assembly-job-list"),
    path("beta/assembly/jobs/<int:pk>/", beta_workshops.assembly_job_detail, name="beta-assembly-job-detail"),
    path("beta/assembly/jobs/<int:pk>/advance/", beta_workshops.assembly_job_advance, name="beta-assembly-job-advance"),
    path("beta/clearance/stats/", beta_workshops.clearance_stats, name="beta-clearance-stats"),
    path("beta/clearance/jobs/", beta_workshops.clearance_job_list, name="beta-clearance-job-list"),
    path("beta/clearance/jobs/<int:pk>/", beta_workshops.clearance_job_detail, name="beta-clearance-job-detail"),
    path("beta/clearance/jobs/<int:pk>/advance/", beta_workshops.clearance_job_advance, name="beta-clearance-job-advance"),
    path("beta/fabric/needs/", beta_workshops.fabric_need_list, name="beta-fabric-need-list"),
    path("beta/fabric/needs/<int:pk>/", beta_workshops.fabric_need_detail, name="beta-fabric-need-detail"),
    path("workshop-recipes/paint-categories/", workshop_recipes.paint_category_list, name="workshop-paint-categories"),
    path("workshop-recipes/fabric-categories/", workshop_recipes.fabric_category_list, name="workshop-fabric-categories"),
    path("workshop-recipes/fabric-companies/", workshop_recipes.fabric_company_list, name="workshop-fabric-companies"),
    path("workshop-recipes/fabric-catalog/", workshop_recipes.fabric_catalog_list, name="workshop-fabric-catalog"),
    path("workshop-recipes/fabric-catalog/<int:pk>/", workshop_recipes.fabric_catalog_detail, name="workshop-fabric-catalog-detail"),
    path("workshop-recipes/", workshop_recipes.recipe_list, name="workshop-recipe-list"),
    path("workshop-recipes/<int:pk>/", workshop_recipes.recipe_detail, name="workshop-recipe-detail"),
    path("audit-logs/", audit_logs.audit_log_list, name="audit-log-list"),
    path("record-filter/catalog/", record_filter.record_filter_catalog, name="record-filter-catalog"),
    path("record-filter/", record_filter.record_filter_query, name="record-filter-query"),
    path("staff/", staff.staff_list, name="staff-list"),
    path("staff/<int:pk>/", staff.staff_detail, name="staff-detail"),
    path("attendance/today/", attendance.attendance_today, name="attendance-today"),
    path("attendance/sale-gate/", attendance.attendance_sale_gate, name="attendance-sale-gate"),
    path("attendance/check-in/", attendance.attendance_check_in, name="attendance-check-in"),
    path("attendance/check-out/", attendance.attendance_check_out, name="attendance-check-out"),
    path(
        "attendance/request-branch-switch/",
        attendance.attendance_request_branch_switch,
        name="attendance-request-branch-switch",
    ),
    path("attendance/<int:pk>/approve/", attendance.attendance_approve, name="attendance-approve"),
    path("attendance/", attendance.attendance_list, name="attendance-list"),
    path("attendance/<int:pk>/", attendance.attendance_detail, name="attendance-detail"),
    path("notifications/", notifications.notification_list, name="notification-list"),
    path("notifications/unread/", notifications.notification_unread, name="notification-unread"),
    path("notifications/read-all/", notifications.notification_read_all, name="notification-read-all"),
    path("notifications/recipients/", notifications.notification_recipients, name="notification-recipients"),
    path("notifications/invoices/", notifications.notification_invoices, name="notification-invoices"),
    path("notifications/messages/", notifications.notification_messages, name="notification-messages"),
    path("notifications/<int:pk>/read/", notifications.notification_read, name="notification-read"),
    path("notifications/<int:pk>/act/", notifications.notification_act, name="notification-act"),
    path("notifications/<int:pk>/replies/", notifications.notification_replies, name="notification-replies"),
    path("notifications/<int:pk>/", notifications.notification_detail, name="notification-detail"),

    # --- Office Forms ---
    path("office-forms/assistance/", office_forms.assistance_requests, name="assistance-requests"),
    path("office-forms/assistance/<int:pk>/", office_forms.assistance_request_detail, name="assistance-request-detail"),
    path("office-forms/assistance/<int:pk>/export-excel/", office_forms.assistance_request_export, name="assistance-request-export"),
    path("office-forms/petty-cash/", office_forms.petty_cash_requests, name="petty-cash-requests"),
    path("office-forms/petty-cash/<int:pk>/", office_forms.petty_cash_detail, name="petty-cash-detail"),
    path("office-forms/petty-cash/<int:pk>/export-excel/", office_forms.petty_cash_export, name="petty-cash-export"),
    path("office-forms/warehouse-transfers/", office_forms.warehouse_transfers, name="warehouse-transfers"),
    path("office-forms/warehouse-transfers/<int:pk>/", office_forms.warehouse_transfer_detail, name="warehouse-transfer-detail"),
    path("office-forms/warehouse-transfers/<int:pk>/export-excel/", office_forms.warehouse_transfer_export, name="warehouse-transfer-export"),
    path("office-forms/production-orders/", office_forms.production_orders, name="production-orders"),
    path("office-forms/production-orders/<int:pk>/", office_forms.production_order_detail, name="production-order-detail"),
    path("office-forms/production-orders/<int:pk>/export-excel/", office_forms.production_order_export, name="production-order-export"),
    path("office-forms/attendance-confirmations/", office_forms.attendance_confirmations, name="attendance-confirmations"),
    path("office-forms/attendance-confirmations/<int:pk>/", office_forms.attendance_confirmation_detail, name="attendance-confirmation-detail"),
    path("office-forms/attendance-confirmations/<int:pk>/export-excel/", office_forms.attendance_confirmation_export, name="attendance-confirmation-export"),

    # --- Accounting ---
    path("accounting/", accounting.entry_list, name="accounting-list"),
    path("accounting/meta/", accounting.meta, name="accounting-meta"),
    path("accounting/accounts/", accounting.account_list, name="accounting-accounts"),
    path("accounting/models/", accounting.document_models, name="accounting-document-models"),
    path("accounting/ledger/", accounting.ledger, name="accounting-ledger"),
    path("accounting/trial-balance/", accounting.trial_balance, name="accounting-trial-balance"),
    path("accounting/statements/", accounting_statements.office_statements, name="accounting-statements"),
    path("accounting/statements/trial-balance/", accounting_statements.office_trial, name="accounting-statements-trial"),
    path("accounting/statements/income/", accounting_statements.office_income, name="accounting-statements-income"),
    path("accounting/statements/balance-sheet/", accounting_statements.office_balance, name="accounting-statements-balance"),
    path("accounting/detail-ledger/", accounting.detail_ledger_view, name="accounting-detail-ledger"),
    path("accounting/documents/", accounting.document_list, name="accounting-document-list"),
    path(
        "accounting/documents/<str:document_code>/submit/",
        accounting.document_submit,
        name="accounting-document-submit",
    ),
    path(
        "accounting/documents/<str:document_code>/approve/",
        accounting.document_approve,
        name="accounting-document-approve",
    ),
    path(
        "accounting/documents/<str:document_code>/",
        accounting.document_detail,
        name="accounting-document-detail",
    ),
    path("accounting/subsidiaries/", accounting.subsidiary_accounts, name="accounting-subsidiaries"),
    path("accounting/subsidiaries/<int:pk>/", accounting.subsidiary_account_detail, name="accounting-subsidiary-detail"),
    path("accounting/details/", accounting.detailed_accounts, name="accounting-details"),
    path("accounting/details/<int:pk>/", accounting.detailed_account_detail, name="accounting-detail-account"),
    path("accounting/accounts/<int:pk>/", accounting.account_detail, name="accounting-account-detail"),
    path("accounting/summary/", accounting.summary, name="accounting-summary"),
    path("accounting/sales-report/", accounting.sales_report, name="accounting-sales-report"),
    path("accounting/bulk-approve/", accounting.bulk_approve, name="accounting-bulk-approve"),
    path("accounting/import-excel/", accounting.excel_import, name="accounting-import-excel"),
    path("accounting/preferences/", accounting.accounting_preferences, name="accounting-preferences"),
    path("accounting/check-accounts/", accounting.check_accounts, name="accounting-check-accounts"),
    path("accounting/profit-centers/", accounting_modules.profit_centers, name="accounting-profit-centers"),
    path("accounting/deposits/", accounting_modules.deposits, name="accounting-deposits"),
    path("accounting/deposits/<int:pk>/allocate/", accounting_modules.deposit_allocate, name="accounting-deposit-allocate"),
    path("accounting/check-plan/", accounting_modules.check_plan, name="accounting-check-plan"),
    path("accounting/books/", accounting_books.office_books, name="accounting-books"),
    path("accounting/books/beancount/", accounting_books.office_books_beancount, name="accounting-books-beancount"),
    path("accounting/books/close/", accounting_books.office_books_close, name="accounting-books-close"),
    path("accounting/books/push/", accounting_books.office_books_push, name="accounting-books-push"),
    path("accounting/trade/", accounting_trade.trade_list, name="accounting-trade"),
    path("accounting/trade/preview/", accounting_trade.trade_preview, name="accounting-trade-preview"),
    path("accounting/trade/purchase/", accounting_trade.trade_purchase, name="accounting-trade-purchase"),
    path("accounting/trade/purchase-return/", accounting_trade.trade_purchase_return, name="accounting-trade-purchase-return"),
    path("accounting/trade/sale/", accounting_trade.trade_sale, name="accounting-trade-sale"),
    path("accounting/trade/sale-return/", accounting_trade.trade_sale_return, name="accounting-trade-sale-return"),
    path("accounting/trade/discount/", accounting_trade.trade_discount, name="accounting-trade-discount"),
    path("accounting/trade/kardex/", accounting_trade.trade_kardex, name="accounting-trade-kardex"),
    path("accounting/payables/overview/", accounting_payables.payable_overview, name="accounting-payables-overview"),
    path("accounting/payables/suppliers/", accounting_payables.suppliers, name="accounting-payables-suppliers"),
    path("accounting/payables/invoices/", accounting_payables.invoices, name="accounting-payables-invoices"),
    path("accounting/payables/settlements/", accounting_payables.settlements, name="accounting-payables-settlements"),
    path("accounting/payables/settle/", accounting_payables.settle, name="accounting-payables-settle"),
    path("accounting/payables/checks/", accounting_payables.checks, name="accounting-payables-checks"),
    path("accounting/payables/checks/<int:pk>/clear/", accounting_payables.check_clear, name="accounting-payables-check-clear"),
    path("accounting/payables/checks/<int:pk>/void/", accounting_payables.check_void, name="accounting-payables-check-void"),
    path("accounting/controls/reconciliation/", accounting_controls.reconciliation, name="accounting-reconciliation"),
    path("accounting/controls/scan/", accounting_controls.discrepancy_scan_view, name="accounting-discrepancy-scan"),
    path("accounting/controls/scan/export/", accounting_controls.discrepancy_scan_export, name="accounting-discrepancy-scan-export"),
    path("accounting/reports/management/", accounting_controls.management_report, name="accounting-management-report"),
    path("accounting/periods/close/", accounting_controls.period_close, name="accounting-period-close"),
    path("accounting/periods/<int:pk>/reopen/", accounting_controls.period_reopen, name="accounting-period-reopen"),
    path("accounting/cost-centers/", accounting_modules.cost_centers, name="accounting-cost-centers"),
    path("accounting/cost-centers/<int:pk>/", accounting_modules.cost_center_detail, name="accounting-cost-center-detail"),
    path("accounting/overhead/", accounting_modules.overhead_periods, name="accounting-overhead"),
    path("accounting/overhead/<int:pk>/allocate/", accounting_modules.overhead_allocate, name="accounting-overhead-allocate"),
    path("accounting/wip-closes/", accounting_modules.wip_closes, name="accounting-wip-closes"),
    path("accounting/spoilage/", accounting_modules.spoilage, name="accounting-spoilage"),
    path("accounting/check-plan/<int:pk>/pay/", accounting_modules.check_plan_pay, name="accounting-check-plan-pay"),
    path(
        "accounting/customer/<int:customer_id>/",
        accounting.customer_accounting,
        name="accounting-customer",
    ),
    path(
        "accounting/<int:pk>/approve/",
        accounting.entry_approve,
        name="accounting-approve",
    ),
    path("accounting/<int:pk>/", accounting.entry_detail, name="accounting-detail"),

    # --- Factory accounting (جدول مجزا) ---
    path("factory-accounting/", factory_accounting.entry_list, name="factory-accounting-list"),
    path("factory-accounting/meta/", factory_accounting.meta, name="factory-accounting-meta"),
    path("factory-accounting/accounts/", factory_accounting.account_list, name="factory-accounting-accounts"),
    path("factory-accounting/models/", factory_accounting.document_models, name="factory-accounting-document-models"),
    path("factory-accounting/ledger/", factory_accounting.ledger, name="factory-accounting-ledger"),
    path("factory-accounting/trial-balance/", factory_accounting.trial_balance, name="factory-accounting-trial-balance"),
    path("factory-accounting/statements/", accounting_statements.factory_statements, name="factory-accounting-statements"),
    path("factory-accounting/statements/trial-balance/", accounting_statements.factory_trial, name="factory-accounting-statements-trial"),
    path("factory-accounting/statements/income/", accounting_statements.factory_income, name="factory-accounting-statements-income"),
    path("factory-accounting/statements/balance-sheet/", accounting_statements.factory_balance, name="factory-accounting-statements-balance"),
    path("factory-accounting/detail-ledger/", factory_accounting.detail_ledger_view, name="factory-accounting-detail-ledger"),
    path("factory-accounting/documents/", factory_accounting.document_list, name="factory-accounting-document-list"),
    path(
        "factory-accounting/documents/<str:document_code>/submit/",
        factory_accounting.document_submit,
        name="factory-accounting-document-submit",
    ),
    path(
        "factory-accounting/documents/<str:document_code>/approve/",
        factory_accounting.document_approve,
        name="factory-accounting-document-approve",
    ),
    path(
        "factory-accounting/documents/<str:document_code>/",
        factory_accounting.document_detail,
        name="factory-accounting-document-detail",
    ),
    path("factory-accounting/subsidiaries/", factory_accounting.subsidiary_accounts, name="factory-accounting-subsidiaries"),
    path("factory-accounting/subsidiaries/<int:pk>/", factory_accounting.subsidiary_account_detail, name="factory-accounting-subsidiary-detail"),
    path("factory-accounting/details/", factory_accounting.detailed_accounts, name="factory-accounting-details"),
    path("factory-accounting/details/<int:pk>/", factory_accounting.detailed_account_detail, name="factory-accounting-detail-account"),
    path("factory-accounting/accounts/<int:pk>/", factory_accounting.account_detail, name="factory-accounting-account-detail"),
    path("factory-accounting/summary/", factory_accounting.summary, name="factory-accounting-summary"),
    path("factory-accounting/bulk-approve/", factory_accounting.bulk_approve, name="factory-accounting-bulk-approve"),
    path("factory-accounting/import-excel/", factory_accounting.excel_import, name="factory-accounting-import-excel"),
    path("factory-accounting/transfer-preview/", factory_accounting.transfer_preview, name="factory-accounting-transfer-preview"),
    path("factory-accounting/transfer/", factory_accounting.transfer_document, name="factory-accounting-transfer"),
    path("factory-accounting/cost-centers/", accounting_modules.cost_centers, name="factory-cost-centers"),
    path("factory-accounting/cost-centers/<int:pk>/", accounting_modules.cost_center_detail, name="factory-cost-center-detail"),
    path("factory-accounting/overhead/", accounting_modules.overhead_periods, name="factory-overhead"),
    path("factory-accounting/overhead/<int:pk>/allocate/", accounting_modules.overhead_allocate, name="factory-overhead-allocate"),
    path("factory-accounting/wip-closes/", accounting_modules.wip_closes, name="factory-wip-closes"),
    path("factory-accounting/spoilage/", accounting_modules.spoilage, name="factory-spoilage"),
    path("factory-accounting/books/", accounting_books.factory_books, name="factory-accounting-books"),
    path("factory-accounting/books/beancount/", accounting_books.factory_books_beancount, name="factory-accounting-books-beancount"),
    path("factory-accounting/books/close/", accounting_books.factory_books_close, name="factory-accounting-books-close"),
    path("factory-accounting/books/push/", accounting_books.factory_books_push, name="factory-accounting-books-push"),
    path("factory-accounting/<int:pk>/approve/", factory_accounting.entry_approve, name="factory-accounting-approve"),
    path("factory-accounting/<int:pk>/", factory_accounting.entry_detail, name="factory-accounting-detail"),

    # --- Loyalty Levels ---
    path("loyalty-levels/", loyalty_levels.level_list, name="loyalty-level-list"),
    path("loyalty-levels/<int:pk>/", loyalty_levels.level_detail, name="loyalty-level-detail"),

    # --- RFM ---
    path("rfm/settings/", rfm.rfm_settings, name="rfm-settings"),
    path("rfm/segments/", rfm.rfm_segment_list, name="rfm-segment-list"),
    path("rfm/segments/<int:pk>/", rfm.rfm_segment_detail, name="rfm-segment-detail"),
    path("rfm/summary/", rfm.rfm_summary, name="rfm-summary"),
    path("rfm/customers/", rfm.rfm_customers, name="rfm-customers"),
    path("rfm/recalculate/", rfm.rfm_recalculate, name="rfm-recalculate"),
    path("rfm/customers/<int:pk>/send-sms/", rfm.rfm_send_sms, name="rfm-send-sms"),
    path("rfm/segments/<int:pk>/send-sms/", rfm.rfm_send_segment_sms, name="rfm-send-segment-sms"),
    path("rfm/cashback/programs/", rfm.rfm_cashback_program_list, name="rfm-cashback-programs"),
    path("rfm/cashback/programs/<int:pk>/", rfm.rfm_cashback_program_detail, name="rfm-cashback-program-detail"),
    path("rfm/cashback/quote/", rfm.rfm_cashback_quote, name="rfm-cashback-quote"),

    # --- SMS ---
    path("sms/logs/", sms.sms_logs, name="sms-logs"),
    path("sms/send/", sms.sms_send, name="sms-send"),
    path("sms/send-to-level/", sms.sms_send_to_level, name="sms-send-to-level"),
    path("sms/send-to-all/", sms.sms_send_to_all, name="sms-send-to-all"),
    path("sms/birthday/settings/", birthday_sms.birthday_settings, name="sms-birthday-settings"),
    path("sms/birthday/preview/", birthday_sms.birthday_preview, name="sms-birthday-preview"),
    path("sms/birthday/exclude/", birthday_sms.birthday_exclude, name="sms-birthday-exclude"),
    path(
        "sms/birthday/exclude/<int:customer_id>/",
        birthday_sms.birthday_unexclude,
        name="sms-birthday-unexclude",
    ),
    path("sms/birthday/send/", birthday_sms.birthday_send, name="sms-birthday-send"),
    path("sms/club/settings/", sms_club.club_settings, name="sms-club-settings"),
    path("sms/club/send-discount/", sms_club.club_send_discount, name="sms-club-send-discount"),
    path("sms/club/discount-preview/", sms_club.club_discount_preview, name="sms-club-discount-preview"),
    path("sms/reminders/", reminder_sms.reminder_list, name="sms-reminder-list"),
    path("sms/reminders/preview/", reminder_sms.reminder_preview, name="sms-reminder-preview"),
    path("sms/reminders/<int:pk>/", reminder_sms.reminder_detail, name="sms-reminder-detail"),
    path("sms/reminders/<int:pk>/send/", reminder_sms.reminder_send, name="sms-reminder-send"),
]
