"""تمام endpointهای API پروژه — پیشوند «/api/» در backend/urls.py."""

from django.urls import path

from api.views import (
    accounting,
    attendance,
    audit_logs,
    auth,
    birthday_sms,
    config,
    customers,
    cycle,
    dashboard,
    factory_accounting,
    factory_orders,
    installments,
    loyalty_levels,
    materials,
    office_orders,
    org_chart,
    products,
    record_filter,
    reminder_sms,
    role_definitions,
    sales,
    sms,
    sms_club,
    staff,
    wallet,
)

urlpatterns = [
    # --- Auth (/api/auth/) ---
    path("auth/login/", auth.login, name="auth-login"),
    path("auth/logout/", auth.logout, name="auth-logout"),
    path("auth/me/", auth.me, name="auth-me"),
    path("auth/roles/", auth.role_list, name="auth-roles"),
    path("auth/users/", auth.user_list, name="auth-users"),
    path("auth/users/<int:pk>/", auth.user_detail, name="auth-user-detail"),
    path("auth/users/<int:pk>/reset-password/", auth.user_reset_password, name="auth-user-reset-password"),
    path("auth/users/<int:pk>/deactivate/", auth.user_deactivate, name="auth-user-deactivate"),
    path("auth/assign-role/", auth.assign_role, name="auth-assign-role"),
    path("auth/change-password/", auth.change_password, name="auth-change-password"),
    path("auth/reset-business-data/", auth.reset_business_data, name="auth-reset-business-data"),
    path("auth/permissions/", role_definitions.permission_matrix, name="auth-permissions"),
    path("auth/role-definitions/", role_definitions.role_definition_list, name="auth-role-definitions"),
    path(
        "auth/role-definitions/<slug:slug>/",
        role_definitions.role_definition_detail,
        name="auth-role-definition-detail",
    ),
    path("auth/org-ranks/", role_definitions.org_rank_list, name="auth-org-ranks"),
    path("auth/org-ranks/<int:pk>/", role_definitions.org_rank_detail, name="auth-org-rank-detail"),
    path("config/", config.app_config, name="app-config"),
    path("config/branches/", config.branch_list, name="config-branches"),
    path("config/branches/<int:pk>/", config.branch_detail, name="config-branch-detail"),
    path("config/lookups/", config.lookup_list, name="config-lookups"),
    path("config/lookups/<int:pk>/", config.lookup_detail, name="config-lookup-detail"),
    path("config/menu-sections/", config.menu_section_list, name="config-menu-sections"),
    path("config/menu-sections/<int:pk>/", config.menu_section_detail, name="config-menu-section-detail"),
    path("config/page-guides/<slug:code>/", config.page_guide_detail, name="config-page-guide-detail"),
    path("config/branding/logo/", config.branding_logo, name="config-branding-logo"),
    path("org-chart/", org_chart.org_chart, name="org-chart"),

    # --- Dashboard ---
    path("dashboard/summary/", dashboard.dashboard_summary, name="dashboard-summary"),

    # --- Customers ---
    path("customers/", customers.customer_list, name="customer-list"),
    path(
        "customers/recalculate-all-levels/",
        customers.recalculate_all_levels,
        name="customer-recalculate-all",
    ),
    path("customers/top-buyers/", customers.customer_top_buyers, name="customer-top-buyers"),
    path("customers/<int:pk>/", customers.customer_detail, name="customer-detail"),
    path(
        "customers/<int:pk>/recalculate-level/",
        customers.recalculate_level,
        name="customer-recalculate-level",
    ),
    path(
        "customers/<int:pk>/history/",
        customers.customer_history,
        name="customer-history",
    ),
    path(
        "customers/<int:pk>/wallet/",
        wallet.customer_wallet,
        name="customer-wallet",
    ),

    # --- Sales ---
    path("sales/reports/daily/", sales.sales_daily_report, name="sales-daily-report"),
    path("sales/reports/weekly/", sales.sales_weekly_report, name="sales-weekly-report"),
    path("sales/reports/monthly/", sales.sales_monthly_report, name="sales-monthly-report"),
    path("sales/reports/daily-breakdown/", sales.sales_daily_breakdown, name="sales-daily-breakdown"),
    path("sales/reports/yearly/", sales.sales_yearly_report, name="sales-yearly-report"),
    path("sales/employee-ranking/", sales.employee_ranking, name="sales-employee-ranking"),
    path("sales/", sales.sale_list, name="sale-list"),
    path("sales/<int:pk>/approve-branch/", sales.sale_approve_branch, name="sale-approve-branch"),
    path("sales/<int:pk>/approve-accounting/", sales.sale_approve_accounting, name="sale-approve-accounting"),
    path("sales/<int:pk>/factory-receive/", sales.sale_factory_receive, name="sale-factory-receive"),
    path("sales/<int:pk>/factory-complete/", sales.sale_factory_complete, name="sale-factory-complete"),
    path("sales/<int:pk>/freight-receive/", sales.sale_freight_receive, name="sale-freight-receive"),
    path("sales/<int:pk>/freight-complete/", sales.sale_freight_complete, name="sale-freight-complete"),
    path("sales/<int:pk>/warehouse-complete/", sales.sale_warehouse_complete, name="sale-warehouse-complete"),
    path("sales/<int:pk>/pickup-complete/", sales.sale_pickup_complete, name="sale-pickup-complete"),
    path("sales/<int:pk>/record-payment/",
        sales.sale_record_payment,
        name="sale-record-payment",
    ),
    path("sales/<int:pk>/confirm/", sales.sale_confirm, name="sale-confirm"),
    path("sales/<int:pk>/cancel/", sales.sale_cancel, name="sale-cancel"),
    path("sales/<int:pk>/export-excel/", sales.sale_export_excel, name="sale-export-excel"),
    path("sales/<int:pk>/", sales.sale_detail, name="sale-detail"),

    # --- Office queue (جدول جدا) ---
    path("office/orders/", office_orders.office_order_list, name="office-order-list"),
    path("office/orders/<int:pk>/", office_orders.office_order_detail, name="office-order-detail"),
    path("office/orders/<int:pk>/approve/", office_orders.office_order_approve, name="office-order-approve"),
    path("office/orders/<int:pk>/reject/", office_orders.office_order_reject, name="office-order-reject"),
    path("office/orders/<int:pk>/rollback/", office_orders.office_order_rollback, name="office-order-rollback"),

    path("cycle/", cycle.cycle_config, name="cycle-config"),
    path("cycle/me/", cycle.cycle_me, name="cycle-me"),
    path("cycle/warehouses/", cycle.warehouse_list, name="cycle-warehouses"),
    path("cycle/warehouses/<int:pk>/", cycle.warehouse_detail, name="cycle-warehouse-detail"),
    path("cycle/watch/", cycle.cycle_watch, name="cycle-watch"),
    path("cycle/warehouse-orders/", cycle.cycle_warehouse_orders, name="cycle-warehouse-orders"),
    path("cycle/pickup-orders/", cycle.cycle_pickup_orders, name="cycle-pickup-orders"),

    # --- Factory queue (جدول جدا) ---
    path("factory/orders/", factory_orders.factory_order_list, name="factory-order-list"),
    path("factory/orders/<int:pk>/", factory_orders.factory_order_detail, name="factory-order-detail"),
    path("factory/orders/<int:pk>/receive/", factory_orders.factory_order_receive, name="factory-order-receive"),
    path("factory/orders/<int:pk>/complete/", factory_orders.factory_order_complete, name="factory-order-complete"),
    path(
        "factory/orders/<int:pk>/freight-receive/",
        factory_orders.factory_order_freight_receive,
        name="factory-order-freight-receive",
    ),
    path(
        "factory/orders/<int:pk>/freight-complete/",
        factory_orders.factory_order_freight_complete,
        name="factory-order-freight-complete",
    ),

    # --- Installments & Checks ---
    path("installments/", installments.installment_list, name="installment-list"),
    path("installments/export-excel/", installments.installments_export_excel, name="installments-export-excel"),
    path("installments/checks-report/", installments.checks_monthly_report, name="checks-report"),
    path("installments/<int:pk>/pay/", installments.installment_pay, name="installment-pay"),
    path("installments/<int:pk>/", installments.installment_detail, name="installment-detail"),

    # --- Attendance ---
    # --- Products ---
    path("products/categories/", products.category_list, name="product-category-list"),
    path("products/categories/<int:pk>/", products.category_detail, name="product-category-detail"),
    path("products/top-selling/", products.product_top_selling, name="product-top-selling"),
    path("products/", products.product_list, name="product-list"),
    path("products/<int:pk>/", products.product_detail, name="product-detail"),
    path("materials/", materials.material_list, name="material-list"),
    path("materials/<int:pk>/", materials.material_detail, name="material-detail"),
    path("materials/<int:pk>/approve/", materials.material_approve, name="material-approve"),
    path("materials/<int:pk>/reject/", materials.material_reject, name="material-reject"),
    path("audit-logs/", audit_logs.audit_log_list, name="audit-log-list"),
    path("record-filter/catalog/", record_filter.record_filter_catalog, name="record-filter-catalog"),
    path("record-filter/", record_filter.record_filter_query, name="record-filter-query"),
    path("staff/", staff.staff_list, name="staff-list"),
    path("staff/<int:pk>/", staff.staff_detail, name="staff-detail"),
    path("attendance/today/", attendance.attendance_today, name="attendance-today"),
    path("attendance/check-in/", attendance.attendance_check_in, name="attendance-check-in"),
    path("attendance/check-out/", attendance.attendance_check_out, name="attendance-check-out"),
    path("attendance/<int:pk>/approve/", attendance.attendance_approve, name="attendance-approve"),
    path("attendance/", attendance.attendance_list, name="attendance-list"),
    path("attendance/<int:pk>/", attendance.attendance_detail, name="attendance-detail"),

    # --- Accounting ---
    path("accounting/", accounting.entry_list, name="accounting-list"),
    path("accounting/meta/", accounting.meta, name="accounting-meta"),
    path("accounting/accounts/", accounting.account_list, name="accounting-accounts"),
    path("accounting/models/", accounting.document_models, name="accounting-document-models"),
    path("accounting/ledger/", accounting.ledger, name="accounting-ledger"),
    path("accounting/trial-balance/", accounting.trial_balance, name="accounting-trial-balance"),
    path("accounting/detail-ledger/", accounting.detail_ledger_view, name="accounting-detail-ledger"),
    path("accounting/documents/", accounting.document_list, name="accounting-document-list"),
    path(
        "accounting/documents/<str:document_code>/approve/",
        accounting.document_approve,
        name="accounting-document-approve",
    ),
    path(
        "accounting/documents/<str:document_code>/",
        accounting.document_detail,
        name="accounting-document-detail",
    ),
    path("accounting/subsidiaries/", accounting.subsidiary_accounts, name="accounting-subsidiaries"),
    path("accounting/subsidiaries/<int:pk>/", accounting.subsidiary_account_detail, name="accounting-subsidiary-detail"),
    path("accounting/details/", accounting.detailed_accounts, name="accounting-details"),
    path("accounting/details/<int:pk>/", accounting.detailed_account_detail, name="accounting-detail-account"),
    path("accounting/accounts/<int:pk>/", accounting.account_detail, name="accounting-account-detail"),
    path("accounting/summary/", accounting.summary, name="accounting-summary"),
    path("accounting/sales-report/", accounting.sales_report, name="accounting-sales-report"),
    path("accounting/bulk-approve/", accounting.bulk_approve, name="accounting-bulk-approve"),
    path("accounting/import-excel/", accounting.excel_import, name="accounting-import-excel"),
    path("accounting/preferences/", accounting.accounting_preferences, name="accounting-preferences"),
    path("accounting/check-accounts/", accounting.check_accounts, name="accounting-check-accounts"),
    path(
        "accounting/customer/<int:customer_id>/",
        accounting.customer_accounting,
        name="accounting-customer",
    ),
    path(
        "accounting/<int:pk>/approve/",
        accounting.entry_approve,
        name="accounting-approve",
    ),
    path("accounting/<int:pk>/", accounting.entry_detail, name="accounting-detail"),

    # --- Factory accounting (جدول مجزا) ---
    path("factory-accounting/", factory_accounting.entry_list, name="factory-accounting-list"),
    path("factory-accounting/meta/", factory_accounting.meta, name="factory-accounting-meta"),
    path("factory-accounting/accounts/", factory_accounting.account_list, name="factory-accounting-accounts"),
    path("factory-accounting/models/", factory_accounting.document_models, name="factory-accounting-document-models"),
    path("factory-accounting/ledger/", factory_accounting.ledger, name="factory-accounting-ledger"),
    path("factory-accounting/trial-balance/", factory_accounting.trial_balance, name="factory-accounting-trial-balance"),
    path("factory-accounting/detail-ledger/", factory_accounting.detail_ledger_view, name="factory-accounting-detail-ledger"),
    path("factory-accounting/documents/", factory_accounting.document_list, name="factory-accounting-document-list"),
    path(
        "factory-accounting/documents/<str:document_code>/approve/",
        factory_accounting.document_approve,
        name="factory-accounting-document-approve",
    ),
    path(
        "factory-accounting/documents/<str:document_code>/",
        factory_accounting.document_detail,
        name="factory-accounting-document-detail",
    ),
    path("factory-accounting/subsidiaries/", factory_accounting.subsidiary_accounts, name="factory-accounting-subsidiaries"),
    path("factory-accounting/subsidiaries/<int:pk>/", factory_accounting.subsidiary_account_detail, name="factory-accounting-subsidiary-detail"),
    path("factory-accounting/details/", factory_accounting.detailed_accounts, name="factory-accounting-details"),
    path("factory-accounting/details/<int:pk>/", factory_accounting.detailed_account_detail, name="factory-accounting-detail-account"),
    path("factory-accounting/accounts/<int:pk>/", factory_accounting.account_detail, name="factory-accounting-account-detail"),
    path("factory-accounting/summary/", factory_accounting.summary, name="factory-accounting-summary"),
    path("factory-accounting/bulk-approve/", factory_accounting.bulk_approve, name="factory-accounting-bulk-approve"),
    path("factory-accounting/import-excel/", factory_accounting.excel_import, name="factory-accounting-import-excel"),
    path("factory-accounting/transfer-preview/", factory_accounting.transfer_preview, name="factory-accounting-transfer-preview"),
    path("factory-accounting/transfer/", factory_accounting.transfer_document, name="factory-accounting-transfer"),
    path("factory-accounting/<int:pk>/approve/", factory_accounting.entry_approve, name="factory-accounting-approve"),
    path("factory-accounting/<int:pk>/", factory_accounting.entry_detail, name="factory-accounting-detail"),

    # --- Loyalty Levels ---
    path("loyalty-levels/", loyalty_levels.level_list, name="loyalty-level-list"),
    path("loyalty-levels/<int:pk>/", loyalty_levels.level_detail, name="loyalty-level-detail"),

    # --- SMS ---
    path("sms/logs/", sms.sms_logs, name="sms-logs"),
    path("sms/send/", sms.sms_send, name="sms-send"),
    path("sms/send-to-level/", sms.sms_send_to_level, name="sms-send-to-level"),
    path("sms/send-to-all/", sms.sms_send_to_all, name="sms-send-to-all"),
    path("sms/birthday/settings/", birthday_sms.birthday_settings, name="sms-birthday-settings"),
    path("sms/birthday/preview/", birthday_sms.birthday_preview, name="sms-birthday-preview"),
    path("sms/birthday/exclude/", birthday_sms.birthday_exclude, name="sms-birthday-exclude"),
    path(
        "sms/birthday/exclude/<int:customer_id>/",
        birthday_sms.birthday_unexclude,
        name="sms-birthday-unexclude",
    ),
    path("sms/birthday/send/", birthday_sms.birthday_send, name="sms-birthday-send"),
    path("sms/club/settings/", sms_club.club_settings, name="sms-club-settings"),
    path("sms/club/send-discount/", sms_club.club_send_discount, name="sms-club-send-discount"),
    path("sms/club/discount-preview/", sms_club.club_discount_preview, name="sms-club-discount-preview"),
    path("sms/reminders/", reminder_sms.reminder_list, name="sms-reminder-list"),
    path("sms/reminders/preview/", reminder_sms.reminder_preview, name="sms-reminder-preview"),
    path("sms/reminders/<int:pk>/", reminder_sms.reminder_detail, name="sms-reminder-detail"),
    path("sms/reminders/<int:pk>/send/", reminder_sms.reminder_send, name="sms-reminder-send"),
]
